class CfgPatches
{
	class NDT_HideVanillaFactions
	{
		name = "Hide Vanilla Factions";
		author = "Nideoth";
		requiredVersion = 2.14;
		requiredAddons[] = {"A3_Data_F_Decade_Loadorder"};
        units[] = {};
		weapons[] = {};
	};
};

class CfgGroups
{
	class West
	{
		delete BLU_F;
		delete Guerilla;
		delete BLU_T_F;
		delete BLU_CTRG_F;
		delete Gendarmerie;
		delete BLU_W_F;
	};
	class East
	{
		delete OPF_F;
		delete OPF_T_F;
		delete OPF_G_F;
		delete OPF_R_F;
	};
	class Indep
	{
		delete IND_F;
		delete IND_C_F;
		delete IND_G_F;
		delete IND_E_F;
		delete IND_L_F;
	};
};

class CfgVehicles
{
	class Civilian_F;
	class C_man_1: Civilian_F {scope=1;scopeCurator=1;};
	class B_Soldier_base_F;
	class B_Soldier_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_RangeMaster_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_Soldier_03_f;
	class B_Soldier_lite_F: B_Soldier_03_f {scope=1;scopeCurator=1;};
	class B_Soldier_GL_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_Soldier_02_f;
	class B_soldier_AR_F: B_Soldier_02_f {scope=1;scopeCurator=1;};
	class B_Soldier_SL_F: B_Soldier_03_f {scope=1;scopeCurator=1;};
	class B_Soldier_TL_F: B_Soldier_03_f {scope=1;scopeCurator=1;};
	class B_soldier_M_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_soldier_LAT_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_medic_F: B_Soldier_02_f {scope=1;scopeCurator=1;};
	class B_soldier_repair_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_soldier_exp_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_Soldier_04_f;
	class B_Helipilot_F: B_Soldier_04_f {scope=1;scopeCurator=1;};
	class B_Soldier_A_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_soldier_AT_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_soldier_AA_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_engineer_F: B_Soldier_03_f {scope=1;scopeCurator=1;};
	class B_crew_F: B_Soldier_03_f {scope=1;scopeCurator=1;};
	class B_officer_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_Competitor_F: B_RangeMaster_F {scope=1;scopeCurator=1;};
	class B_Soldier_05_f;
	class B_Pilot_F: B_Soldier_05_f {scope=1;scopeCurator=1;};
	class B_helicrew_F: B_Helipilot_F {scope=1;scopeCurator=1;};
	class B_soldier_PG_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_soldier_UAV_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_Survivor_F: B_Soldier_F {scope=1;scopeCurator=1;};
	class B_Soldier_unarmed_F: B_Soldier_F {scope=1;scopeCurator=1;};
	class B_Soldier_diver_base_F;
	class B_diver_F: B_Soldier_diver_base_F {scope=1;scopeCurator=1;};
	class B_diver_TL_F: B_Soldier_diver_base_F {scope=1;scopeCurator=1;};
	class B_diver_exp_F: B_Soldier_diver_base_F {scope=1;scopeCurator=1;};
	class B_Soldier_recon_base;
	class B_recon_F: B_Soldier_recon_base {scope=1;scopeCurator=1;};
	class B_recon_LAT_F: B_Soldier_recon_base {scope=1;scopeCurator=1;};
	class B_recon_exp_F: B_Soldier_recon_base {scope=1;scopeCurator=1;};
	class B_recon_medic_F: B_Soldier_recon_base {scope=1;scopeCurator=1;};
	class B_recon_TL_F: B_Soldier_recon_base {scope=1;scopeCurator=1;};
	class B_recon_M_F: B_Soldier_recon_base {scope=1;scopeCurator=1;};
	class B_recon_JTAC_F: B_Soldier_recon_base {scope=1;scopeCurator=1;};
	class B_Soldier_sniper_base_F;
	class B_spotter_F: B_Soldier_sniper_base_F {scope=1;scopeCurator=1;};
	class B_sniper_F: B_Soldier_sniper_base_F {scope=1;scopeCurator=1;};
	class B_Story_SF_Captain_F: B_Soldier_02_f {scope=1;scopeCurator=1;};
	class B_Story_Protagonist_F: B_Soldier_02_f {scope=1;scopeCurator=1;};
	class B_Story_Pilot_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_CTRG_soldier_GL_LAT_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_CTRG_soldier_engineer_exp_F: B_Soldier_02_f {scope=1;scopeCurator=1;};
	class B_CTRG_soldier_M_medic_F: B_Soldier_03_f {scope=1;scopeCurator=1;};
	class B_CTRG_soldier_AR_A_F: B_Soldier_03_f {scope=1;scopeCurator=1;};
	class B_Soldier_support_base_F;
	class B_soldier_AAR_F: B_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class B_soldier_AAT_F: B_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class B_soldier_AAA_F: B_soldier_AAT_F {scope=1;scopeCurator=1;};
	class B_support_MG_F: B_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class B_support_GMG_F: B_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class B_support_Mort_F: B_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class B_support_AMG_F: B_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class B_support_AMort_F: B_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class C_man_1_1_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_man_1_2_F: C_man_1_1_F {scope=1;scopeCurator=1;};
	class C_man_1_3_F: C_man_1_1_F {scope=1;scopeCurator=1;};
	class C_man_polo_1_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_man_polo_1_F_afro: C_man_polo_1_F {scope=1;scopeCurator=1;};
	class C_man_polo_1_F_euro: C_man_polo_1_F {scope=1;scopeCurator=1;};
	class C_man_polo_1_F_asia: C_man_polo_1_F {scope=1;scopeCurator=1;};
	class C_man_polo_2_F: C_man_polo_1_F {scope=1;scopeCurator=1;};
	class C_man_polo_2_F_afro: C_man_polo_2_F {scope=1;scopeCurator=1;};
	class C_man_polo_2_F_euro: C_man_polo_2_F {scope=1;scopeCurator=1;};
	class C_man_polo_2_F_asia: C_man_polo_2_F {scope=1;scopeCurator=1;};
	class C_man_polo_3_F: C_man_polo_1_F {scope=1;scopeCurator=1;};
	class C_man_polo_3_F_afro: C_man_polo_3_F {scope=1;scopeCurator=1;};
	class C_man_polo_3_F_euro: C_man_polo_3_F {scope=1;scopeCurator=1;};
	class C_man_polo_3_F_asia: C_man_polo_3_F {scope=1;scopeCurator=1;};
	class C_man_polo_4_F: C_man_polo_1_F {scope=1;scopeCurator=1;};
	class C_man_polo_4_F_afro: C_man_polo_4_F {scope=1;scopeCurator=1;};
	class C_man_polo_4_F_euro: C_man_polo_4_F {scope=1;scopeCurator=1;};
	class C_man_polo_4_F_asia: C_man_polo_4_F {scope=1;scopeCurator=1;};
	class C_man_polo_5_F: C_man_polo_1_F {scope=1;scopeCurator=1;};
	class C_man_polo_5_F_afro: C_man_polo_5_F {scope=1;scopeCurator=1;};
	class C_man_polo_5_F_euro: C_man_polo_5_F {scope=1;scopeCurator=1;};
	class C_man_polo_5_F_asia: C_man_polo_5_F {scope=1;scopeCurator=1;};
	class C_man_polo_6_F: C_man_polo_1_F {scope=1;scopeCurator=1;};
	class C_man_polo_6_F_afro: C_man_polo_6_F {scope=1;scopeCurator=1;};
	class C_man_polo_6_F_euro: C_man_polo_6_F {scope=1;scopeCurator=1;};
	class C_man_polo_6_F_asia: C_man_polo_6_F {scope=1;scopeCurator=1;};
	class C_man_p_fugitive_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_man_p_fugitive_F_afro: C_man_p_fugitive_F {scope=1;scopeCurator=1;};
	class C_man_p_fugitive_F_euro: C_man_p_fugitive_F {scope=1;scopeCurator=1;};
	class C_man_p_fugitive_F_asia: C_man_p_fugitive_F {scope=1;scopeCurator=1;};
	class C_man_p_beggar_F: C_man_p_fugitive_F {scope=1;scopeCurator=1;};
	class C_man_p_beggar_F_afro: C_man_p_beggar_F {scope=1;scopeCurator=1;};
	class C_man_p_beggar_F_euro: C_man_p_beggar_F {scope=1;scopeCurator=1;};
	class C_man_p_beggar_F_asia: C_man_p_beggar_F {scope=1;scopeCurator=1;};
	class C_man_w_worker_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_scientist_F: C_man_w_worker_F {scope=1;scopeCurator=1;};
	class C_man_hunter_1_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_man_p_shorts_1_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_man_p_shorts_1_F_afro: C_man_p_shorts_1_F {scope=1;scopeCurator=1;};
	class C_man_p_shorts_1_F_euro: C_man_p_shorts_1_F {scope=1;scopeCurator=1;};
	class C_man_p_shorts_1_F_asia: C_man_p_shorts_1_F {scope=1;scopeCurator=1;};
	class C_man_shorts_1_F: C_man_p_shorts_1_F {scope=1;scopeCurator=1;};
	class C_man_shorts_1_F_afro: C_man_shorts_1_F {scope=1;scopeCurator=1;};
	class C_man_shorts_1_F_euro: C_man_shorts_1_F {scope=1;scopeCurator=1;};
	class C_man_shorts_1_F_asia: C_man_shorts_1_F {scope=1;scopeCurator=1;};
	class C_man_shorts_2_F: C_man_p_shorts_1_F {scope=1;scopeCurator=1;};
	class C_man_shorts_2_F_afro: C_man_shorts_2_F {scope=1;scopeCurator=1;};
	class C_man_shorts_2_F_euro: C_man_shorts_2_F {scope=1;scopeCurator=1;};
	class C_man_shorts_2_F_asia: C_man_shorts_2_F {scope=1;scopeCurator=1;};
	class C_man_shorts_3_F: C_man_p_shorts_1_F {scope=1;scopeCurator=1;};
	class C_man_shorts_3_F_afro: C_man_shorts_3_F {scope=1;scopeCurator=1;};
	class C_man_shorts_3_F_euro: C_man_shorts_3_F {scope=1;scopeCurator=1;};
	class C_man_shorts_3_F_asia: C_man_shorts_3_F {scope=1;scopeCurator=1;};
	class C_man_shorts_4_F: C_man_p_shorts_1_F {scope=1;scopeCurator=1;};
	class C_man_shorts_4_F_afro: C_man_shorts_4_F {scope=1;scopeCurator=1;};
	class C_man_shorts_4_F_euro: C_man_shorts_4_F {scope=1;scopeCurator=1;};
	class C_man_shorts_4_F_asia: C_man_shorts_4_F {scope=1;scopeCurator=1;};
	class C_man_pilot_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_journalist_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_Orestes: C_man_1 {scope=1;scopeCurator=1;};
	class C_Nikos: C_Orestes {scope=1;scopeCurator=1;};
	class C_Nikos_aged: C_Nikos {scope=1;scopeCurator=1;};
	class I_G_Soldier_base_F;
	class I_G_Soldier_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_lite_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_SL_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_TL_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_AR_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_medic_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_engineer_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_exp_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_GL_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_M_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_LAT_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_A_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_G_officer_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_F: I_G_Soldier_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_F: I_G_Soldier_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_lite_F: I_G_Soldier_lite_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_lite_F: I_G_Soldier_lite_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_SL_F: I_G_Soldier_SL_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_SL_F: I_G_Soldier_SL_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_TL_F: I_G_Soldier_TL_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_TL_F: I_G_Soldier_TL_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_AR_F: I_G_Soldier_AR_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_AR_F: I_G_Soldier_AR_F {scope=1;scopeCurator=1;};
	class B_G_medic_F: I_G_medic_F {scope=1;scopeCurator=1;};
	class O_G_medic_F: I_G_medic_F {scope=1;scopeCurator=1;};
	class B_G_engineer_F: I_G_engineer_F {scope=1;scopeCurator=1;};
	class O_G_engineer_F: I_G_engineer_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_exp_F: I_G_Soldier_exp_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_exp_F: I_G_Soldier_exp_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_GL_F: I_G_Soldier_GL_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_GL_F: I_G_Soldier_GL_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_M_F: I_G_Soldier_M_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_M_F: I_G_Soldier_M_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_LAT_F: I_G_Soldier_LAT_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_LAT_F: I_G_Soldier_LAT_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_A_F: I_G_Soldier_A_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_A_F: I_G_Soldier_A_F {scope=1;scopeCurator=1;};
	class B_G_officer_F: I_G_officer_F {scope=1;scopeCurator=1;};
	class O_G_officer_F: I_G_officer_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_unarmed_F: I_G_Soldier_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_unarmed_F: B_G_Soldier_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_unarmed_F: O_G_Soldier_F {scope=1;scopeCurator=1;};
	class I_G_Survivor_F: I_G_Soldier_F {scope=1;scopeCurator=1;};
	class B_G_Survivor_F: B_G_Soldier_F {scope=1;scopeCurator=1;};
	class O_G_Survivor_F: O_G_Soldier_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_universal_F: B_G_Soldier_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_universal_F: O_G_Soldier_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_universal_F: I_G_Soldier_F {scope=1;scopeCurator=1;};
	class I_G_Story_Protagonist_F: B_G_Soldier_F {scope=1;scopeCurator=1;};
	class I_G_Story_SF_Captain_F: B_G_Soldier_F {scope=1;scopeCurator=1;};
	class I_G_resistanceLeader_F: I_G_Story_Protagonist_F {scope=1;scopeCurator=1;};
	class I_Soldier_base_F;
	class I_soldier_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_02_F;
	class I_Soldier_lite_F: I_Soldier_02_F {scope=1;scopeCurator=1;};
	class I_Soldier_A_F: I_Soldier_02_F {scope=1;scopeCurator=1;};
	class I_Soldier_GL_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_AR_F: I_Soldier_02_F {scope=1;scopeCurator=1;};
	class I_Soldier_SL_F: I_Soldier_02_F {scope=1;scopeCurator=1;};
	class I_Soldier_TL_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_M_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_LAT_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_AT_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_AA_F: I_Soldier_02_F {scope=1;scopeCurator=1;};
	class I_medic_F: I_Soldier_02_F {scope=1;scopeCurator=1;};
	class I_Soldier_repair_F: I_Soldier_02_F {scope=1;scopeCurator=1;};
	class I_Soldier_exp_F: I_Soldier_02_F {scope=1;scopeCurator=1;};
	class I_engineer_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_crew_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_03_F;
	class I_helipilot_F: I_Soldier_03_F {scope=1;scopeCurator=1;};
	class I_Soldier_04_F;
	class I_pilot_F: I_Soldier_04_F {scope=1;scopeCurator=1;};
	class I_helicrew_F: I_helipilot_F {scope=1;scopeCurator=1;};
	class I_officer_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Story_Colonel_F: I_officer_F {scope=1;scopeCurator=1;};
	class I_soldier_UAV_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Survivor_F: I_soldier_F {scope=1;scopeCurator=1;};
	class I_Soldier_unarmed_F: I_soldier_F {scope=1;scopeCurator=1;};
	class I_Soldier_diver_base_F;
	class I_diver_F: I_Soldier_diver_base_F {scope=1;scopeCurator=1;};
	class I_diver_exp_F: I_Soldier_diver_base_F {scope=1;scopeCurator=1;};
	class I_diver_TL_F: I_Soldier_diver_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_sniper_base_F;
	class I_Spotter_F: I_Soldier_sniper_base_F {scope=1;scopeCurator=1;};
	class I_Sniper_F: I_Soldier_sniper_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_support_base_F;
	class I_Soldier_AAR_F: I_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_AAT_F: I_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_AAA_F: I_Soldier_AAT_F {scope=1;scopeCurator=1;};
	class I_support_MG_F: I_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class I_support_GMG_F: I_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class I_support_Mort_F: I_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class I_support_AMG_F: I_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class I_support_AMort_F: I_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_base_F;
	class O_Soldier_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_officer_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_lite_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_GL_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_AR_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_SL_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_TL_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_soldier_M_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_LAT_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_medic_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_soldier_repair_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_soldier_exp_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_02_F;
	class O_helipilot_F: O_Soldier_02_F {scope=1;scopeCurator=1;};
	class O_Soldier_A_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_AT_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_AA_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_engineer_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_crew_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Pilot_F: O_helipilot_F {scope=1;scopeCurator=1;};
	class O_helicrew_F: O_helipilot_F {scope=1;scopeCurator=1;};
	class O_soldier_PG_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Story_Colonel_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Story_CEO_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_soldier_UAV_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Survivor_F: O_Soldier_F {scope=1;scopeCurator=1;};
	class O_Soldier_unarmed_F: O_Soldier_F {scope=1;scopeCurator=1;};
	class O_Soldier_diver_base_F;
	class O_diver_F: O_Soldier_diver_base_F {scope=1;scopeCurator=1;};
	class O_diver_TL_F: O_Soldier_diver_base_F {scope=1;scopeCurator=1;};
	class O_diver_exp_F: O_Soldier_diver_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_sniper_base_F;
	class O_spotter_F: O_Soldier_sniper_base_F {scope=1;scopeCurator=1;};
	class O_sniper_F: O_Soldier_sniper_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_recon_base;
	class O_recon_F: O_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_recon_M_F: O_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_recon_LAT_F: O_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_recon_medic_F: O_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_recon_exp_F: O_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_recon_JTAC_F: O_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_recon_TL_F: O_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_Soldier_support_base_F;
	class O_Soldier_AAR_F: O_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_AAT_F: O_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_AAA_F: O_Soldier_AAT_F {scope=1;scopeCurator=1;};
	class O_support_MG_F: O_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class O_support_GMG_F: O_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class O_support_Mort_F: O_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class O_support_AMG_F: O_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class O_support_AMort_F: O_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_Urban_base;
	class O_soldierU_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_AR_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_AAR_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_LAT_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_AT_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_AAT_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_AA_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_AAA_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_TL_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_SoldierU_SL_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_medic_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_repair_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_exp_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_engineer_U_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_M_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_soldierU_A_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_SoldierU_GL_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_SoldierU_unarmed_F: O_soldierU_F {scope=1;scopeCurator=1;};
	class C_Driver_1_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_Driver_2_F: C_Driver_1_F {scope=1;scopeCurator=1;};
	class C_Driver_3_F: C_Driver_1_F {scope=1;scopeCurator=1;};
	class C_Driver_4_F: C_Driver_1_F {scope=1;scopeCurator=1;};
	class C_Marshal_F: B_RangeMaster_F {scope=1;scopeCurator=1;};
	class B_Soldier_VR_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_VR_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Soldier_VR_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class C_Soldier_VR_F: C_man_1 {scope=1;scopeCurator=1;};
	class B_Protagonist_VR_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Protagonist_VR_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_Protagonist_VR_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class C_Protagonist_VR_F: C_man_1 {scope=1;scopeCurator=1;};
	class B_ghillie_base_F;
	class B_ghillie_lsh_F: B_ghillie_base_F {scope=1;scopeCurator=1;};
	class B_ghillie_sard_F: B_ghillie_base_F {scope=1;scopeCurator=1;};
	class B_ghillie_ard_F: B_ghillie_base_F {scope=1;scopeCurator=1;};
	class O_ghillie_base_F;
	class O_ghillie_lsh_F: O_ghillie_base_F {scope=1;scopeCurator=1;};
	class O_ghillie_sard_F: O_ghillie_base_F {scope=1;scopeCurator=1;};
	class O_ghillie_ard_F: O_ghillie_base_F {scope=1;scopeCurator=1;};
	class I_ghillie_base_F;
	class I_ghillie_lsh_F: I_ghillie_base_F {scope=1;scopeCurator=1;};
	class I_ghillie_sard_F: I_ghillie_base_F {scope=1;scopeCurator=1;};
	class I_ghillie_ard_F: I_ghillie_base_F {scope=1;scopeCurator=1;};
	class B_Sharpshooter_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_Recon_Sharpshooter_F: B_Soldier_recon_base {scope=1;scopeCurator=1;};
	class B_CTRG_Sharphooter_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_HeavyGunner_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Sharpshooter_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Urban_Sharpshooter_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class O_Pathfinder_F: O_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_HeavyGunner_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Urban_HeavyGunner_F: O_Soldier_Urban_base {scope=1;scopeCurator=1;};
	class I_G_Sharpshooter_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_G_Sharpshooter_F: I_G_Sharpshooter_F {scope=1;scopeCurator=1;};
	class O_G_Sharpshooter_F: I_G_Sharpshooter_F {scope=1;scopeCurator=1;};
	class B_Captain_Pettka_F: B_Soldier_02_f {scope=1;scopeCurator=1;};
	class B_Captain_Jay_F: B_Soldier_02_f {scope=1;scopeCurator=1;};
	class I_Captain_Hladas_F: I_officer_F {scope=1;scopeCurator=1;};
	class HMG_01_base_F;
	class B_HMG_01_F: HMG_01_base_F {scope=1;scopeCurator=1;};
	class O_HMG_01_F: HMG_01_base_F {scope=1;scopeCurator=1;};
	class I_HMG_01_F: HMG_01_base_F {scope=1;scopeCurator=1;};
	class HMG_01_high_base_F;
	class B_HMG_01_high_F: HMG_01_high_base_F {scope=1;scopeCurator=1;};
	class O_HMG_01_high_F: HMG_01_high_base_F {scope=1;scopeCurator=1;};
	class I_HMG_01_high_F: HMG_01_high_base_F {scope=1;scopeCurator=1;};
	class HMG_01_A_base_F;
	class B_HMG_01_A_F: HMG_01_A_base_F {scope=1;scopeCurator=1;};
	class O_HMG_01_A_F: HMG_01_A_base_F {scope=1;scopeCurator=1;};
	class I_HMG_01_A_F: HMG_01_A_base_F {scope=1;scopeCurator=1;};
	class GMG_01_base_F;
	class B_GMG_01_F: GMG_01_base_F {scope=1;scopeCurator=1;};
	class O_GMG_01_F: GMG_01_base_F {scope=1;scopeCurator=1;};
	class I_GMG_01_F: GMG_01_base_F {scope=1;scopeCurator=1;};
	class GMG_01_high_base_F;
	class B_GMG_01_high_F: GMG_01_high_base_F {scope=1;scopeCurator=1;};
	class O_GMG_01_high_F: GMG_01_high_base_F {scope=1;scopeCurator=1;};
	class I_GMG_01_high_F: GMG_01_high_base_F {scope=1;scopeCurator=1;};
	class GMG_01_A_base_F;
	class B_GMG_01_A_F: GMG_01_A_base_F {scope=1;scopeCurator=1;};
	class O_GMG_01_A_F: GMG_01_A_base_F {scope=1;scopeCurator=1;};
	class I_GMG_01_A_F: GMG_01_A_base_F {scope=1;scopeCurator=1;};
	class HMG_02_base_F;
	class I_HMG_02_F: HMG_02_base_F {scope=1;scopeCurator=1;};
	class I_E_HMG_02_F: HMG_02_base_F {scope=1;scopeCurator=1;};
	class I_G_HMG_02_F: HMG_02_base_F {scope=1;scopeCurator=1;};
	class B_G_HMG_02_F: HMG_02_base_F {scope=1;scopeCurator=1;};
	class O_G_HMG_02_F: HMG_02_base_F {scope=1;scopeCurator=1;};
	class I_C_HMG_02_F: HMG_02_base_F {scope=1;scopeCurator=1;};
	class HMG_02_high_base_F;
	class I_HMG_02_high_F: HMG_02_high_base_F {scope=1;scopeCurator=1;};
	class I_E_HMG_02_high_F: HMG_02_high_base_F {scope=1;scopeCurator=1;};
	class I_G_HMG_02_high_F: HMG_02_high_base_F {scope=1;scopeCurator=1;};
	class B_G_HMG_02_high_F: HMG_02_high_base_F {scope=1;scopeCurator=1;};
	class O_G_HMG_02_high_F: HMG_02_high_base_F {scope=1;scopeCurator=1;};
	class I_C_HMG_02_high_F: HMG_02_high_base_F {scope=1;scopeCurator=1;};
	class Mortar_01_base_F;
	class B_Mortar_01_F: Mortar_01_base_F {scope=1;scopeCurator=1;};
	class O_Mortar_01_F: Mortar_01_base_F {scope=1;scopeCurator=1;};
	class I_Mortar_01_F: Mortar_01_base_F {scope=1;scopeCurator=1;};
	class I_G_Mortar_01_F: Mortar_01_base_F {scope=1;scopeCurator=1;};
	class B_G_Mortar_01_F: I_G_Mortar_01_F {scope=1;scopeCurator=1;};
	class O_G_Mortar_01_F: I_G_Mortar_01_F {scope=1;scopeCurator=1;};
	class Heli_Light_01_unarmed_base_F;
	class B_Heli_Light_01_F: Heli_Light_01_unarmed_base_F {scope=1;scopeCurator=1;};
	class Heli_Light_01_dynamicLoadout_base_F;
	class B_Heli_Light_01_dynamicLoadout_F: Heli_Light_01_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class Heli_Light_01_civil_base_F;
	class C_Heli_Light_01_civil_F: Heli_Light_01_civil_base_F {scope=1;scopeCurator=1;};
	class Heli_Light_02_dynamicLoadout_base_F;
	class O_Heli_Light_02_dynamicLoadout_F: Heli_Light_02_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class Heli_Light_02_unarmed_base_F;
	class O_Heli_Light_02_unarmed_F: Heli_Light_02_unarmed_base_F {scope=1;scopeCurator=1;};
	class Heli_Attack_01_dynamicLoadout_base_F;
	class B_Heli_Attack_01_dynamicLoadout_F: Heli_Attack_01_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class Heli_Attack_02_dynamicLoadout_base_F;
	class O_Heli_Attack_02_dynamicLoadout_F: Heli_Attack_02_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class Heli_Transport_01_base_F;
	class B_Heli_Transport_01_F: Heli_Transport_01_base_F {scope=1;scopeCurator=1;};
	class Heli_Transport_02_base_F;
	class I_Heli_Transport_02_F: Heli_Transport_02_base_F {scope=1;scopeCurator=1;};
	class Plane_Fighter_03_base_F;
	class I_Plane_Fighter_03_CAS_F: Plane_Fighter_03_base_F {scope=1;scopeCurator=1;};
	class I_Plane_Fighter_03_AA_F: I_Plane_Fighter_03_CAS_F {scope=1;scopeCurator=1;};
	class Plane_Fighter_03_dynamicLoadout_base_F;
	class I_Plane_Fighter_03_dynamicLoadout_F: Plane_Fighter_03_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class B_APC_Tracked_01_base_F;
	class B_APC_Tracked_01_rcws_F: B_APC_Tracked_01_base_F {scope=1;scopeCurator=1;};
	class B_APC_Tracked_01_CRV_F: B_APC_Tracked_01_base_F {scope=1;scopeCurator=1;};
	class B_APC_Tracked_01_AA_F: B_APC_Tracked_01_base_F {scope=1;scopeCurator=1;};
	class O_APC_Tracked_02_base_F;
	class O_APC_Tracked_02_cannon_F: O_APC_Tracked_02_base_F {scope=1;scopeCurator=1;};
	class O_APC_Tracked_02_AA_F: O_APC_Tracked_02_base_F {scope=1;scopeCurator=1;};
	class B_MBT_01_base_F;
	class B_MBT_01_cannon_F: B_MBT_01_base_F {scope=1;scopeCurator=1;};
	class B_MBT_01_arty_base_F;
	class B_MBT_01_arty_F: B_MBT_01_arty_base_F {scope=1;scopeCurator=1;};
	class B_MBT_01_mlrs_base_F;
	class B_MBT_01_mlrs_F: B_MBT_01_mlrs_base_F {scope=1;scopeCurator=1;};
	class O_MBT_02_base_F;
	class O_MBT_02_cannon_F: O_MBT_02_base_F {scope=1;scopeCurator=1;};
	class O_MBT_02_arty_base_F;
	class O_MBT_02_arty_F: O_MBT_02_arty_base_F {scope=1;scopeCurator=1;};
	class Boat_Armed_01_minigun_base_F;
	class B_Boat_Armed_01_minigun_F: Boat_Armed_01_minigun_base_F {scope=1;scopeCurator=1;};
	class Boat_Armed_01_base_F;
	class O_Boat_Armed_01_hmg_F: Boat_Armed_01_base_F {scope=1;scopeCurator=1;};
	class Rubber_duck_base_F;
	class B_Boat_Transport_01_F: Rubber_duck_base_F {scope=1;scopeCurator=1;};
	class O_Boat_Transport_01_F: Rubber_duck_base_F {scope=1;scopeCurator=1;};
	class Rescue_duck_base_F;
	class B_Lifeboat: Rescue_duck_base_F {scope=1;scopeCurator=1;};
	class O_Lifeboat: Rescue_duck_base_F {scope=1;scopeCurator=1;};
	class C_Rubberboat: Rescue_duck_base_F {scope=1;scopeCurator=1;};
	class I_Boat_Armed_01_minigun_F: Boat_Armed_01_minigun_base_F {scope=1;scopeCurator=1;};
	class I_Boat_Transport_01_F: Rubber_duck_base_F {scope=1;scopeCurator=1;};
	class SDV_01_base_F;
	class B_SDV_01_F: SDV_01_base_F {scope=1;scopeCurator=1;};
	class O_SDV_01_F: SDV_01_base_F {scope=1;scopeCurator=1;};
	class I_SDV_01_F: SDV_01_base_F {scope=1;scopeCurator=1;};
	class Boat_Civil_01_base_F;
	class C_Boat_Civil_01_F: Boat_Civil_01_base_F {scope=1;scopeCurator=1;};
	class C_Boat_Civil_01_rescue_F: Boat_Civil_01_base_F {scope=1;scopeCurator=1;};
	class C_Boat_Civil_01_police_F: Boat_Civil_01_base_F {scope=1;scopeCurator=1;};
	class I_G_Boat_Transport_01_F: Rubber_duck_base_F {scope=1;scopeCurator=1;};
	class B_G_Boat_Transport_01_F: I_G_Boat_Transport_01_F {scope=1;scopeCurator=1;};
	class O_G_Boat_Transport_01_F: I_G_Boat_Transport_01_F {scope=1;scopeCurator=1;};
	class MRAP_01_base_F;
	class B_MRAP_01_F: MRAP_01_base_F {scope=1;scopeCurator=1;};
	class MRAP_01_gmg_base_F;
	class B_MRAP_01_gmg_F: MRAP_01_gmg_base_F {scope=1;scopeCurator=1;};
	class MRAP_01_hmg_base_F;
	class B_MRAP_01_hmg_F: MRAP_01_hmg_base_F {scope=1;scopeCurator=1;};
	class MRAP_02_base_F;
	class O_MRAP_02_F: MRAP_02_base_F {scope=1;scopeCurator=1;};
	class MRAP_02_hmg_base_F;
	class O_MRAP_02_hmg_F: MRAP_02_hmg_base_F {scope=1;scopeCurator=1;};
	class MRAP_02_gmg_base_F;
	class O_MRAP_02_gmg_F: MRAP_02_gmg_base_F {scope=1;scopeCurator=1;};
	class Offroad_01_civil_base_F;
	class C_Offroad_01_F: Offroad_01_civil_base_F {scope=1;scopeCurator=1;};
	class Offroad_01_repair_base_F;
	class C_Offroad_01_repair_F: Offroad_01_repair_base_F {scope=1;scopeCurator=1;};
	class Offroad_01_repair_military_base_F;
	class B_G_Offroad_01_repair_F: Offroad_01_repair_military_base_F {scope=1;scopeCurator=1;};
	class O_G_Offroad_01_repair_F: Offroad_01_repair_military_base_F {scope=1;scopeCurator=1;};
	class I_G_Offroad_01_repair_F: Offroad_01_repair_military_base_F {scope=1;scopeCurator=1;};
	class Offroad_01_military_base_F;
	class I_G_Offroad_01_F: Offroad_01_military_base_F {scope=1;scopeCurator=1;};
	class Offroad_01_AT_base_F;
	class I_G_Offroad_01_AT_F: Offroad_01_AT_base_F {scope=1;scopeCurator=1;};
	class Offroad_01_armed_base_F;
	class I_G_Offroad_01_armed_F: Offroad_01_armed_base_F {scope=1;scopeCurator=1;};
	class B_G_Offroad_01_F: I_G_Offroad_01_F {scope=1;scopeCurator=1;};
	class O_G_Offroad_01_F: I_G_Offroad_01_F {scope=1;scopeCurator=1;};
	class B_G_Offroad_01_armed_F: I_G_Offroad_01_armed_F {scope=1;scopeCurator=1;};
	class O_G_Offroad_01_armed_F: I_G_Offroad_01_armed_F {scope=1;scopeCurator=1;};
	class B_G_Offroad_01_AT_F: I_G_Offroad_01_AT_F {scope=1;scopeCurator=1;};
	class O_G_Offroad_01_AT_F: I_G_Offroad_01_AT_F {scope=1;scopeCurator=1;};
	class Quadbike_01_base_F;
	class C_Quadbike_01_F: Quadbike_01_base_F {scope=1;scopeCurator=1;};
	class B_Quadbike_01_F: Quadbike_01_base_F {scope=1;scopeCurator=1;};
	class O_Quadbike_01_F: Quadbike_01_base_F {scope=1;scopeCurator=1;};
	class I_Quadbike_01_F: Quadbike_01_base_F {scope=1;scopeCurator=1;};
	class I_G_Quadbike_01_F: Quadbike_01_base_F {scope=1;scopeCurator=1;};
	class B_G_Quadbike_01_F: I_G_Quadbike_01_F {scope=1;scopeCurator=1;};
	class O_G_Quadbike_01_F: I_G_Quadbike_01_F {scope=1;scopeCurator=1;};
	class MRAP_03_base_F;
	class I_MRAP_03_F: MRAP_03_base_F {scope=1;scopeCurator=1;};
	class MRAP_03_hmg_base_F;
	class I_MRAP_03_hmg_F: MRAP_03_hmg_base_F {scope=1;scopeCurator=1;};
	class MRAP_03_gmg_base_F;
	class I_MRAP_03_gmg_F: MRAP_03_gmg_base_F {scope=1;scopeCurator=1;};
	class Truck_01_base_F;
	class B_Truck_01_transport_F: Truck_01_base_F {scope=1;scopeCurator=1;};
	class B_Truck_01_covered_F: B_Truck_01_transport_F {scope=1;scopeCurator=1;};
	class Truck_02_base_F;
	class O_Truck_02_covered_F: Truck_02_base_F {scope=1;scopeCurator=1;};
	class Truck_02_transport_base_F;
	class O_Truck_02_transport_F: Truck_02_transport_base_F {scope=1;scopeCurator=1;};
	class I_Truck_02_covered_F: Truck_02_base_F {scope=1;scopeCurator=1;};
	class I_Truck_02_transport_F: Truck_02_transport_base_F {scope=1;scopeCurator=1;};
	class C_Truck_02_covered_F: Truck_02_base_F {scope=1;scopeCurator=1;};
	class C_Truck_02_transport_F: Truck_02_transport_base_F {scope=1;scopeCurator=1;};
	class Hatchback_01_base_F;
	class C_Hatchback_01_F: Hatchback_01_base_F {scope=1;scopeCurator=1;};
	class Hatchback_01_sport_base_F;
	class C_Hatchback_01_sport_F: Hatchback_01_sport_base_F {scope=1;scopeCurator=1;};
	class SUV_01_base_F;
	class C_SUV_01_F: SUV_01_base_F {scope=1;scopeCurator=1;};
	class B_Truck_01_mover_F: B_Truck_01_transport_F {scope=1;scopeCurator=1;};
	class B_Truck_01_box_F: B_Truck_01_mover_F {scope=1;scopeCurator=1;};
	class B_Truck_01_Repair_F: B_Truck_01_mover_F {scope=1;scopeCurator=1;};
	class B_Truck_01_ammo_F: B_Truck_01_mover_F {scope=1;scopeCurator=1;};
	class B_Truck_01_fuel_F: B_Truck_01_mover_F {scope=1;scopeCurator=1;};
	class B_Truck_01_medical_F: B_Truck_01_transport_F {scope=1;scopeCurator=1;};
	class Truck_02_box_base_F;
	class O_Truck_02_box_F: Truck_02_box_base_F {scope=1;scopeCurator=1;};
	class Truck_02_medical_base_F;
	class O_Truck_02_medical_F: Truck_02_medical_base_F {scope=1;scopeCurator=1;};
	class Truck_02_Ammo_base_F;
	class O_Truck_02_Ammo_F: Truck_02_Ammo_base_F {scope=1;scopeCurator=1;};
	class Truck_02_fuel_base_F;
	class O_Truck_02_fuel_F: Truck_02_fuel_base_F {scope=1;scopeCurator=1;};
	class I_Truck_02_ammo_F: Truck_02_Ammo_base_F {scope=1;scopeCurator=1;};
	class I_Truck_02_box_F: Truck_02_box_base_F {scope=1;scopeCurator=1;};
	class I_Truck_02_medical_F: Truck_02_medical_base_F {scope=1;scopeCurator=1;};
	class I_Truck_02_fuel_F: Truck_02_fuel_base_F {scope=1;scopeCurator=1;};
	class Truck_02_MRL_base_F;
	class I_Truck_02_MRL_F: Truck_02_MRL_base_F {scope=1;scopeCurator=1;};
	class C_Truck_02_fuel_F: Truck_02_fuel_base_F {scope=1;scopeCurator=1;};
	class C_Truck_02_box_F: Truck_02_box_base_F {scope=1;scopeCurator=1;};
	class Van_01_transport_base_F;
	class C_Van_01_transport_F: Van_01_transport_base_F {scope=1;scopeCurator=1;};
	class I_G_Van_01_transport_F: Van_01_transport_base_F {scope=1;scopeCurator=1;};
	class Van_01_box_base_F;
	class C_Van_01_box_F: Van_01_box_base_F {scope=1;scopeCurator=1;};
	class Van_01_fuel_base_F;
	class C_Van_01_fuel_F: Van_01_fuel_base_F {scope=1;scopeCurator=1;};
	class I_G_Van_01_fuel_F: Van_01_fuel_base_F {scope=1;scopeCurator=1;};
	class B_G_Van_01_transport_F: I_G_Van_01_transport_F {scope=1;scopeCurator=1;};
	class O_G_Van_01_transport_F: I_G_Van_01_transport_F {scope=1;scopeCurator=1;};
	class B_G_Van_01_fuel_F: I_G_Van_01_fuel_F {scope=1;scopeCurator=1;};
	class O_G_Van_01_fuel_F: I_G_Van_01_fuel_F {scope=1;scopeCurator=1;};
	class AA_01_base_F;
	class B_static_AA_F: AA_01_base_F {scope=1;scopeCurator=1;};
	class O_static_AA_F: AA_01_base_F {scope=1;scopeCurator=1;};
	class I_static_AA_F: AA_01_base_F {scope=1;scopeCurator=1;};
	class AT_01_base_F;
	class B_static_AT_F: AT_01_base_F {scope=1;scopeCurator=1;};
	class O_static_AT_F: AT_01_base_F {scope=1;scopeCurator=1;};
	class I_static_AT_F: AT_01_base_F {scope=1;scopeCurator=1;};
	class Heli_light_03_dynamicLoadout_base_F;
	class I_Heli_light_03_dynamicLoadout_F: Heli_light_03_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class Heli_light_03_unarmed_base_F;
	class I_Heli_light_03_unarmed_F: Heli_light_03_unarmed_base_F {scope=1;scopeCurator=1;};
	class Plane_CAS_01_dynamicLoadout_base_F;
	class B_Plane_CAS_01_dynamicLoadout_F: Plane_CAS_01_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class Plane_CAS_02_dynamicLoadout_base_F;
	class O_Plane_CAS_02_dynamicLoadout_F: Plane_CAS_02_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class B_APC_Wheeled_01_base_F;
	class B_APC_Wheeled_01_cannon_F: B_APC_Wheeled_01_base_F {scope=1;scopeCurator=1;};
	class APC_Wheeled_02_base_v2_F;
	class O_APC_Wheeled_02_rcws_v2_F: APC_Wheeled_02_base_v2_F {scope=1;scopeCurator=1;};
	class I_APC_tracked_03_base_F;
	class I_APC_tracked_03_cannon_F: I_APC_tracked_03_base_F {scope=1;scopeCurator=1;};
	class I_MBT_03_base_F;
	class I_MBT_03_cannon_F: I_MBT_03_base_F {scope=1;scopeCurator=1;};
	class B_MBT_01_TUSK_F: B_MBT_01_cannon_F {scope=1;scopeCurator=1;};
	class I_APC_Wheeled_03_base_F;
	class I_APC_Wheeled_03_cannon_F: I_APC_Wheeled_03_base_F {scope=1;scopeCurator=1;};
	class UAV_01_base_F;
	class B_UAV_01_F: UAV_01_base_F {scope=1;scopeCurator=1;};
	class O_UAV_01_F: UAV_01_base_F {scope=1;scopeCurator=1;};
	class I_UAV_01_F: UAV_01_base_F {scope=1;scopeCurator=1;};
	class UAV_02_base_F;
	class B_UAV_02_F: UAV_02_base_F {scope=1;scopeCurator=1;};
	class O_UAV_02_F: UAV_02_base_F {scope=1;scopeCurator=1;};
	class I_UAV_02_F: UAV_02_base_F {scope=1;scopeCurator=1;};
	class UAV_02_CAS_base_F;
	class B_UAV_02_CAS_F: UAV_02_CAS_base_F {scope=1;scopeCurator=1;};
	class O_UAV_02_CAS_F: UAV_02_CAS_base_F {scope=1;scopeCurator=1;};
	class I_UAV_02_CAS_F: UAV_02_CAS_base_F {scope=1;scopeCurator=1;};
	class UAV_02_dynamicLoadout_base_F;
	class B_UAV_02_dynamicLoadout_F: UAV_02_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class O_UAV_02_dynamicLoadout_F: UAV_02_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class I_UAV_02_dynamicLoadout_F: UAV_02_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class UGV_01_base_F;
	class B_UGV_01_F: UGV_01_base_F {scope=1;scopeCurator=1;};
	class O_UGV_01_F: UGV_01_base_F {scope=1;scopeCurator=1;};
	class I_UGV_01_F: UGV_01_base_F {scope=1;scopeCurator=1;};
	class UGV_01_rcws_base_F;
	class B_UGV_01_rcws_F: UGV_01_rcws_base_F {scope=1;scopeCurator=1;};
	class O_UGV_01_rcws_F: UGV_01_rcws_base_F {scope=1;scopeCurator=1;};
	class I_UGV_01_rcws_F: UGV_01_rcws_base_F {scope=1;scopeCurator=1;};
	class Truck_03_base_F;
	class O_Truck_03_transport_F: Truck_03_base_F {scope=1;scopeCurator=1;};
	class O_Truck_03_covered_F: Truck_03_base_F {scope=1;scopeCurator=1;};
	class O_Truck_03_repair_F: Truck_03_base_F {scope=1;scopeCurator=1;};
	class O_Truck_03_ammo_F: Truck_03_base_F {scope=1;scopeCurator=1;};
	class O_Truck_03_fuel_F: Truck_03_base_F {scope=1;scopeCurator=1;};
	class O_Truck_03_medical_F: Truck_03_base_F {scope=1;scopeCurator=1;};
	class O_Truck_03_device_F: Truck_03_base_F {scope=1;scopeCurator=1;};
	class C_Kart_01_F_Base;
	class C_Kart_01_F: C_Kart_01_F_Base {scope=1;scopeCurator=1;};
	class C_Kart_01_Fuel_F: C_Kart_01_F_Base {scope=1;scopeCurator=1;};
	class C_Kart_01_Blu_F: C_Kart_01_F_Base {scope=1;scopeCurator=1;};
	class C_Kart_01_Red_F: C_Kart_01_F_Base {scope=1;scopeCurator=1;};
	class C_Kart_01_Vrana_F: C_Kart_01_F_Base {scope=1;scopeCurator=1;};
	class Heli_Transport_03_base_F;
	class B_Heli_Transport_03_F: Heli_Transport_03_base_F {scope=1;scopeCurator=1;};
	class Heli_Transport_03_unarmed_base_F;
	class B_Heli_Transport_03_unarmed_F: Heli_Transport_03_unarmed_base_F {scope=1;scopeCurator=1;};
	class Heli_Transport_04_base_F;
	class O_Heli_Transport_04_F: Heli_Transport_04_base_F {scope=1;scopeCurator=1;};
	class O_Heli_Transport_04_ammo_F: Heli_Transport_04_base_F {scope=1;scopeCurator=1;};
	class O_Heli_Transport_04_bench_F: Heli_Transport_04_base_F {scope=1;scopeCurator=1;};
	class O_Heli_Transport_04_box_F: Heli_Transport_04_base_F {scope=1;scopeCurator=1;};
	class O_Heli_Transport_04_covered_F: Heli_Transport_04_base_F {scope=1;scopeCurator=1;};
	class O_Heli_Transport_04_fuel_F: Heli_Transport_04_base_F {scope=1;scopeCurator=1;};
	class O_Heli_Transport_04_medevac_F: Heli_Transport_04_base_F {scope=1;scopeCurator=1;};
	class O_Heli_Transport_04_repair_F: Heli_Transport_04_base_F {scope=1;scopeCurator=1;};
	class Pod_Heli_Transport_04_crewed_base_F;
	class Land_Pod_Heli_Transport_04_bench_F: Pod_Heli_Transport_04_crewed_base_F {scope=1;scopeCurator=1;};
	class Land_Pod_Heli_Transport_04_covered_F: Pod_Heli_Transport_04_crewed_base_F {scope=1;scopeCurator=1;};
	class Land_Pod_Heli_Transport_04_medevac_F: Pod_Heli_Transport_04_crewed_base_F {scope=1;scopeCurator=1;};
	class Static_Designator_01_base_F;
	class B_Static_Designator_01_F: Static_Designator_01_base_F {scope=1;scopeCurator=1;};
	class Static_Designator_02_base_F;
	class O_Static_Designator_02_F: Static_Designator_02_base_F {scope=1;scopeCurator=1;};
	class LSV_01_armed_base_F;
	class B_T_LSV_01_armed_F: LSV_01_armed_base_F {scope=1;scopeCurator=1;};
	class LSV_01_AT_base_F;
	class B_T_LSV_01_AT_F: LSV_01_AT_base_F {scope=1;scopeCurator=1;};
	class LSV_01_unarmed_base_F;
	class B_T_LSV_01_unarmed_F: LSV_01_unarmed_base_F {scope=1;scopeCurator=1;};
	class B_LSV_01_armed_F: LSV_01_armed_base_F {scope=1;scopeCurator=1;};
	class B_LSV_01_AT_F: LSV_01_AT_base_F {scope=1;scopeCurator=1;};
	class B_LSV_01_unarmed_F: LSV_01_unarmed_base_F {scope=1;scopeCurator=1;};
	class LSV_01_light_base_F;
	class B_CTRG_LSV_01_light_F: LSV_01_light_base_F {scope=1;scopeCurator=1;};
	class LSV_02_armed_base_F;
	class O_T_LSV_02_armed_F: LSV_02_armed_base_F {scope=1;scopeCurator=1;};
	class LSV_02_unarmed_base_F;
	class O_T_LSV_02_unarmed_F: LSV_02_unarmed_base_F {scope=1;scopeCurator=1;};
	class LSV_02_AT_base_F;
	class O_T_LSV_02_AT_F: LSV_02_AT_base_F {scope=1;scopeCurator=1;};
	class O_LSV_02_armed_F: LSV_02_armed_base_F {scope=1;scopeCurator=1;};
	class O_LSV_02_unarmed_F: LSV_02_unarmed_base_F {scope=1;scopeCurator=1;};
	class O_LSV_02_AT_F: LSV_02_AT_base_F {scope=1;scopeCurator=1;};
	class B_T_MRAP_01_F: B_MRAP_01_F {scope=1;scopeCurator=1;};
	class B_T_MRAP_01_gmg_F: B_MRAP_01_gmg_F {scope=1;scopeCurator=1;};
	class B_T_MRAP_01_hmg_F: B_MRAP_01_hmg_F {scope=1;scopeCurator=1;};
	class O_T_MRAP_02_ghex_F: MRAP_02_base_F {scope=1;scopeCurator=1;};
	class O_T_MRAP_02_hmg_ghex_F: MRAP_02_hmg_base_F {scope=1;scopeCurator=1;};
	class O_T_MRAP_02_gmg_ghex_F: MRAP_02_gmg_base_F {scope=1;scopeCurator=1;};
	class B_GEN_Offroad_01_gen_F: Offroad_01_civil_base_F {scope=1;scopeCurator=1;};
	class Offroad_02_unarmed_base_F;
	class C_Offroad_02_unarmed_F: Offroad_02_unarmed_base_F {scope=1;scopeCurator=1;};
	class I_C_Offroad_02_unarmed_F: Offroad_02_unarmed_base_F {scope=1;scopeCurator=1;};
	class Offroad_02_LMG_base_F;
	class I_C_Offroad_02_LMG_F: Offroad_02_LMG_base_F {scope=1;scopeCurator=1;};
	class Offroad_02_AT_base_F;
	class I_C_Offroad_02_AT_F: Offroad_02_AT_base_F {scope=1;scopeCurator=1;};
	class O_T_Quadbike_01_ghex_F: Quadbike_01_base_F {scope=1;scopeCurator=1;};
	class B_T_Quadbike_01_F: Quadbike_01_base_F {scope=1;scopeCurator=1;};
	class B_T_Truck_01_transport_F: B_Truck_01_transport_F {scope=1;scopeCurator=1;};
	class B_T_Truck_01_covered_F: B_Truck_01_covered_F {scope=1;scopeCurator=1;};
	class B_T_Truck_01_mover_F: B_Truck_01_mover_F {scope=1;scopeCurator=1;};
	class B_T_Truck_01_box_F: B_Truck_01_box_F {scope=1;scopeCurator=1;};
	class B_T_Truck_01_Repair_F: B_Truck_01_Repair_F {scope=1;scopeCurator=1;};
	class B_T_Truck_01_ammo_F: B_Truck_01_ammo_F {scope=1;scopeCurator=1;};
	class B_T_Truck_01_fuel_F: B_Truck_01_fuel_F {scope=1;scopeCurator=1;};
	class B_T_Truck_01_medical_F: B_Truck_01_medical_F {scope=1;scopeCurator=1;};
	class O_T_Truck_02_F: Truck_02_base_F {scope=1;scopeCurator=1;};
	class O_T_Truck_02_transport_F: Truck_02_transport_base_F {scope=1;scopeCurator=1;};
	class O_T_Truck_02_fuel_F: Truck_02_fuel_base_F {scope=1;scopeCurator=1;};
	class O_T_Truck_02_Ammo_F: Truck_02_Ammo_base_F {scope=1;scopeCurator=1;};
	class O_T_Truck_02_Box_F: Truck_02_box_base_F {scope=1;scopeCurator=1;};
	class O_T_Truck_02_Medical_F: Truck_02_medical_base_F {scope=1;scopeCurator=1;};
	class O_T_Truck_03_transport_ghex_F: O_Truck_03_transport_F {scope=1;scopeCurator=1;};
	class O_T_Truck_03_covered_ghex_F: O_Truck_03_covered_F {scope=1;scopeCurator=1;};
	class O_T_Truck_03_repair_ghex_F: O_Truck_03_repair_F {scope=1;scopeCurator=1;};
	class O_T_Truck_03_ammo_ghex_F: O_Truck_03_ammo_F {scope=1;scopeCurator=1;};
	class O_T_Truck_03_fuel_ghex_F: O_Truck_03_fuel_F {scope=1;scopeCurator=1;};
	class O_T_Truck_03_medical_ghex_F: O_Truck_03_medical_F {scope=1;scopeCurator=1;};
	class O_T_Truck_03_device_ghex_F: O_Truck_03_device_F {scope=1;scopeCurator=1;};
	class O_T_UGV_01_ghex_F: UGV_01_base_F {scope=1;scopeCurator=1;};
	class O_T_UGV_01_rcws_ghex_F: UGV_01_rcws_base_F {scope=1;scopeCurator=1;};
	class B_T_UGV_01_olive_F: UGV_01_base_F {scope=1;scopeCurator=1;};
	class B_T_UGV_01_rcws_olive_F: UGV_01_rcws_base_F {scope=1;scopeCurator=1;};
	class I_C_Van_01_transport_F: Van_01_transport_base_F {scope=1;scopeCurator=1;};
	class B_T_Static_AA_F: B_static_AA_F {scope=1;scopeCurator=1;};
	class B_T_Static_AT_F: B_static_AT_F {scope=1;scopeCurator=1;};
	class B_T_GMG_01_F: B_GMG_01_F {scope=1;scopeCurator=1;};
	class B_T_HMG_01_F: B_HMG_01_F {scope=1;scopeCurator=1;};
	class B_T_Mortar_01_F: B_Mortar_01_F {scope=1;scopeCurator=1;};
	class I_C_Heli_Light_01_civil_F: Heli_Light_01_civil_base_F {scope=1;scopeCurator=1;};
	class B_CTRG_Heli_Transport_01_sand_F: Heli_Transport_01_base_F {scope=1;scopeCurator=1;};
	class B_CTRG_Heli_Transport_01_tropic_F: Heli_Transport_01_base_F {scope=1;scopeCurator=1;};
	class Plane_Civil_01_base_F;
	class C_Plane_Civil_01_F: Plane_Civil_01_base_F {scope=1;scopeCurator=1;};
	class C_Plane_Civil_01_racing_F: Plane_Civil_01_base_F {scope=1;scopeCurator=1;};
	class I_C_Plane_Civil_01_F: Plane_Civil_01_base_F {scope=1;scopeCurator=1;};
	class UAV_03_dynamicLoadout_base_F;
	class B_T_UAV_03_dynamicLoadout_F: UAV_03_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class UAV_04_base_F;
	class O_T_UAV_04_CAS_F: UAV_04_base_F {scope=1;scopeCurator=1;};
	class VTOL_01_infantry_base_F;
	class B_T_VTOL_01_infantry_F: VTOL_01_infantry_base_F {scope=1;scopeCurator=1;};
	class VTOL_01_vehicle_base_F;
	class B_T_VTOL_01_vehicle_F: VTOL_01_vehicle_base_F {scope=1;scopeCurator=1;};
	class VTOL_01_armed_base_F;
	class B_T_VTOL_01_armed_F: VTOL_01_armed_base_F {scope=1;scopeCurator=1;};
	class VTOL_02_infantry_dynamicLoadout_base_F;
	class O_T_VTOL_02_infantry_dynamicLoadout_F: VTOL_02_infantry_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class VTOL_02_vehicle_dynamicLoadout_base_F;
	class O_T_VTOL_02_vehicle_dynamicLoadout_F: VTOL_02_vehicle_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class B_T_APC_Tracked_01_AA_F: B_APC_Tracked_01_AA_F {scope=1;scopeCurator=1;};
	class B_T_APC_Tracked_01_CRV_F: B_APC_Tracked_01_CRV_F {scope=1;scopeCurator=1;};
	class B_T_APC_Tracked_01_rcws_F: B_APC_Tracked_01_rcws_F {scope=1;scopeCurator=1;};
	class O_T_APC_Tracked_02_cannon_ghex_F: O_APC_Tracked_02_cannon_F {scope=1;scopeCurator=1;};
	class O_T_APC_Tracked_02_AA_ghex_F: O_APC_Tracked_02_AA_F {scope=1;scopeCurator=1;};
	class B_T_APC_Wheeled_01_cannon_F: B_APC_Wheeled_01_cannon_F {scope=1;scopeCurator=1;};
	class O_T_APC_Wheeled_02_rcws_v2_ghex_F: APC_Wheeled_02_base_v2_F {scope=1;scopeCurator=1;};
	class B_T_MBT_01_arty_F: B_MBT_01_arty_F {scope=1;scopeCurator=1;};
	class B_T_MBT_01_mlrs_F: B_MBT_01_mlrs_F {scope=1;scopeCurator=1;};
	class B_T_MBT_01_cannon_F: B_MBT_01_cannon_F {scope=1;scopeCurator=1;};
	class B_T_MBT_01_TUSK_F: B_MBT_01_TUSK_F {scope=1;scopeCurator=1;};
	class O_T_MBT_02_cannon_ghex_F: O_MBT_02_cannon_F {scope=1;scopeCurator=1;};
	class O_T_MBT_02_arty_ghex_F: O_MBT_02_arty_F {scope=1;scopeCurator=1;};
	class B_T_Boat_Armed_01_minigun_F: B_Boat_Armed_01_minigun_F {scope=1;scopeCurator=1;};
	class O_T_Boat_Armed_01_hmg_F: O_Boat_Armed_01_hmg_F {scope=1;scopeCurator=1;};
	class O_T_Boat_Transport_01_F: Rubber_duck_base_F {scope=1;scopeCurator=1;};
	class I_C_Boat_Transport_01_F: Rubber_duck_base_F {scope=1;scopeCurator=1;};
	class B_T_Boat_Transport_01_F: B_Boat_Transport_01_F {scope=1;scopeCurator=1;};
	class B_T_Lifeboat: B_Lifeboat {scope=1;scopeCurator=1;};
	class O_T_Lifeboat: O_Lifeboat {scope=1;scopeCurator=1;};
	class Boat_Transport_02_base_F;
	class I_C_Boat_Transport_02_F: Boat_Transport_02_base_F {scope=1;scopeCurator=1;};
	class C_Boat_Transport_02_F: Boat_Transport_02_base_F {scope=1;scopeCurator=1;};
	class Scooter_Transport_01_base_F;
	class C_Scooter_Transport_01_F: Scooter_Transport_01_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_base_F;
	class I_C_Soldier_Para_1_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Para_2_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Para_3_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Para_4_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Para_5_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Para_6_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Para_7_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Para_8_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Bandit_1_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Bandit_2_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Bandit_3_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Bandit_4_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Bandit_5_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Bandit_6_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Bandit_7_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Bandit_8_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_Camo_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Pilot_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Helipilot_F: I_C_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_universal_F: I_C_Soldier_Para_1_F {scope=1;scopeCurator=1;};
	class I_C_Soldier_base_unarmed_F: I_C_Soldier_Para_1_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_A_F: B_Soldier_A_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_AAR_F: B_soldier_AAR_F {scope=1;scopeCurator=1;};
	class B_T_Support_AMG_F: B_support_AMG_F {scope=1;scopeCurator=1;};
	class B_T_Support_AMort_F: B_support_AMort_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_AAA_F: B_soldier_AAA_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_AAT_F: B_soldier_AAT_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_AR_F: B_soldier_AR_F {scope=1;scopeCurator=1;};
	class B_T_Medic_F: B_medic_F {scope=1;scopeCurator=1;};
	class B_T_Crew_F: B_crew_F {scope=1;scopeCurator=1;};
	class B_T_Engineer_F: B_engineer_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_Exp_F: B_soldier_exp_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_GL_F: B_Soldier_GL_F {scope=1;scopeCurator=1;};
	class B_T_Support_GMG_F: B_support_GMG_F {scope=1;scopeCurator=1;};
	class B_T_Support_MG_F: B_support_MG_F {scope=1;scopeCurator=1;};
	class B_T_Support_Mort_F: B_support_Mort_F {scope=1;scopeCurator=1;};
	class B_T_Helicrew_F: B_helicrew_F {scope=1;scopeCurator=1;};
	class B_T_Helipilot_F: B_Helipilot_F {scope=1;scopeCurator=1;};
	class B_T_soldier_M_F: B_soldier_M_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_AA_F: B_soldier_AA_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_AT_F: B_soldier_AT_F {scope=1;scopeCurator=1;};
	class B_T_Officer_F: B_officer_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_PG_F: B_soldier_PG_F {scope=1;scopeCurator=1;};
	class B_T_Pilot_F: B_Pilot_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_Repair_F: B_soldier_repair_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_F: B_Soldier_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_LAT_F: B_soldier_LAT_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_SL_F: B_Soldier_SL_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_TL_F: B_Soldier_TL_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_UAV_F: B_soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_T_Diver_F: B_diver_F {scope=1;scopeCurator=1;};
	class B_T_Diver_Exp_F: B_diver_exp_F {scope=1;scopeCurator=1;};
	class B_T_Diver_TL_F: B_diver_TL_F {scope=1;scopeCurator=1;};
	class B_T_Recon_Exp_F: B_recon_exp_F {scope=1;scopeCurator=1;};
	class B_T_Recon_JTAC_F: B_recon_JTAC_F {scope=1;scopeCurator=1;};
	class B_T_Recon_M_F: B_recon_M_F {scope=1;scopeCurator=1;};
	class B_T_Recon_Medic_F: B_recon_medic_F {scope=1;scopeCurator=1;};
	class B_T_Recon_F: B_recon_F {scope=1;scopeCurator=1;};
	class B_T_Recon_LAT_F: B_recon_LAT_F {scope=1;scopeCurator=1;};
	class B_T_Recon_TL_F: B_recon_TL_F {scope=1;scopeCurator=1;};
	class B_T_Sniper_F: B_sniper_F {scope=1;scopeCurator=1;};
	class B_T_Spotter_F: B_spotter_F {scope=1;scopeCurator=1;};
	class B_T_ghillie_tna_F: B_ghillie_base_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_unarmed_F: B_T_Soldier_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_A_F: O_Soldier_A_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_AAR_F: O_Soldier_AAR_F {scope=1;scopeCurator=1;};
	class O_T_Support_AMG_F: O_support_AMG_F {scope=1;scopeCurator=1;};
	class O_T_Support_AMort_F: O_support_AMort_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_AAA_F: O_Soldier_AAA_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_AAT_F: O_Soldier_AAT_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_AR_F: O_Soldier_AR_F {scope=1;scopeCurator=1;};
	class O_T_Medic_F: O_medic_F {scope=1;scopeCurator=1;};
	class O_T_Crew_F: O_crew_F {scope=1;scopeCurator=1;};
	class O_T_Engineer_F: O_engineer_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_Exp_F: O_soldier_exp_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_GL_F: O_Soldier_GL_F {scope=1;scopeCurator=1;};
	class O_T_Support_GMG_F: O_support_GMG_F {scope=1;scopeCurator=1;};
	class O_T_Support_MG_F: O_support_MG_F {scope=1;scopeCurator=1;};
	class O_T_Support_Mort_F: O_support_Mort_F {scope=1;scopeCurator=1;};
	class O_T_Helicrew_F: O_helicrew_F {scope=1;scopeCurator=1;};
	class O_T_Helipilot_F: O_helipilot_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_M_F: O_soldier_M_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_AA_F: O_Soldier_AA_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_AT_F: O_Soldier_AT_F {scope=1;scopeCurator=1;};
	class O_T_Officer_F: O_officer_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_PG_F: O_soldier_PG_F {scope=1;scopeCurator=1;};
	class O_T_Pilot_F: O_Pilot_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_Repair_F: O_soldier_repair_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_F: O_Soldier_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_LAT_F: O_Soldier_LAT_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_SL_F: O_Soldier_SL_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_TL_F: O_Soldier_TL_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_UAV_F: O_soldier_UAV_F {scope=1;scopeCurator=1;};
	class O_T_Diver_F: O_diver_F {scope=1;scopeCurator=1;};
	class O_T_Diver_Exp_F: O_diver_exp_F {scope=1;scopeCurator=1;};
	class O_T_Diver_TL_F: O_diver_TL_F {scope=1;scopeCurator=1;};
	class O_T_Recon_Exp_F: O_recon_exp_F {scope=1;scopeCurator=1;};
	class O_T_Recon_JTAC_F: O_recon_JTAC_F {scope=1;scopeCurator=1;};
	class O_T_Recon_M_F: O_recon_M_F {scope=1;scopeCurator=1;};
	class O_T_Recon_Medic_F: O_recon_medic_F {scope=1;scopeCurator=1;};
	class O_T_Recon_F: O_recon_F {scope=1;scopeCurator=1;};
	class O_T_Recon_LAT_F: O_recon_LAT_F {scope=1;scopeCurator=1;};
	class O_T_Recon_TL_F: O_recon_TL_F {scope=1;scopeCurator=1;};
	class O_T_Sniper_F: O_sniper_F {scope=1;scopeCurator=1;};
	class O_T_Spotter_F: O_spotter_F {scope=1;scopeCurator=1;};
	class O_T_ghillie_tna_F: O_ghillie_base_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_unarmed_F: O_T_Soldier_F {scope=1;scopeCurator=1;};
	class B_CTRG_Soldier_F;
	class B_CTRG_Soldier_TL_tna_F: B_CTRG_Soldier_F {scope=1;scopeCurator=1;};
	class B_CTRG_Soldier_Exp_tna_F: B_CTRG_Soldier_F {scope=1;scopeCurator=1;};
	class B_CTRG_Soldier_Medic_tna_F: B_CTRG_Soldier_F {scope=1;scopeCurator=1;};
	class B_CTRG_Soldier_M_tna_F: B_CTRG_Soldier_F {scope=1;scopeCurator=1;};
	class B_CTRG_Soldier_tna_F: B_CTRG_Soldier_F {scope=1;scopeCurator=1;};
	class B_CTRG_Soldier_LAT_tna_F: B_CTRG_Soldier_F {scope=1;scopeCurator=1;};
	class B_CTRG_Soldier_AR_tna_F: B_CTRG_Soldier_F {scope=1;scopeCurator=1;};
	class B_CTRG_Soldier_JTAC_tna_F: B_CTRG_Soldier_F {scope=1;scopeCurator=1;};
	class B_CTRG_Soldier_3_F;
	class B_CTRG_Miller_F: B_CTRG_Soldier_3_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_base_F;
	class O_V_Soldier_hex_F: O_V_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_TL_hex_F: O_V_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_Exp_hex_F: O_V_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_Medic_hex_F: O_V_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_M_hex_F: O_V_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_LAT_hex_F: O_V_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_JTAC_hex_F: O_V_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_ghex_F: O_V_Soldier_hex_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_TL_ghex_F: O_V_Soldier_TL_hex_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_Exp_ghex_F: O_V_Soldier_Exp_hex_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_Medic_ghex_F: O_V_Soldier_Medic_hex_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_M_ghex_F: O_V_Soldier_M_hex_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_LAT_ghex_F: O_V_Soldier_LAT_hex_F {scope=1;scopeCurator=1;};
	class O_V_Soldier_JTAC_ghex_F: O_V_Soldier_JTAC_hex_F {scope=1;scopeCurator=1;};
	class B_GEN_Soldier_base_F;
	class B_GEN_Soldier_F: B_GEN_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_GEN_Commander_F: B_GEN_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_Captain_Dwarden_F: B_GEN_Commander_F {scope=1;scopeCurator=1;};
	class B_G_Captain_Ivan_F: I_C_Soldier_Para_2_F {scope=1;scopeCurator=1;};
	class C_man_sport_1_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_man_sport_1_F_afro: C_man_sport_1_F {scope=1;scopeCurator=1;};
	class C_man_sport_1_F_euro: C_man_sport_1_F {scope=1;scopeCurator=1;};
	class C_man_sport_1_F_asia: C_man_sport_1_F {scope=1;scopeCurator=1;};
	class C_man_sport_1_F_tanoan: C_man_sport_1_F {scope=1;scopeCurator=1;};
	class C_man_sport_2_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_man_sport_2_F_afro: C_man_sport_2_F {scope=1;scopeCurator=1;};
	class C_man_sport_2_F_euro: C_man_sport_2_F {scope=1;scopeCurator=1;};
	class C_man_sport_2_F_asia: C_man_sport_2_F {scope=1;scopeCurator=1;};
	class C_man_sport_2_F_tanoan: C_man_sport_2_F {scope=1;scopeCurator=1;};
	class C_man_sport_3_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_man_sport_3_F_afro: C_man_sport_3_F {scope=1;scopeCurator=1;};
	class C_man_sport_3_F_euro: C_man_sport_3_F {scope=1;scopeCurator=1;};
	class C_man_sport_3_F_asia: C_man_sport_3_F {scope=1;scopeCurator=1;};
	class C_man_sport_3_F_tanoan: C_man_sport_3_F {scope=1;scopeCurator=1;};
	class C_Man_casual_1_F: C_man_1 {scope=1;scopeCurator=1;};
	class C_Man_casual_1_F_afro: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_1_F_euro: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_1_F_asia: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_1_F_tanoan: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_2_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_2_F_afro: C_Man_casual_2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_2_F_euro: C_Man_casual_2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_2_F_asia: C_Man_casual_2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_2_F_tanoan: C_Man_casual_2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_3_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_3_F_afro: C_Man_casual_3_F {scope=1;scopeCurator=1;};
	class C_Man_casual_3_F_euro: C_Man_casual_3_F {scope=1;scopeCurator=1;};
	class C_Man_casual_3_F_asia: C_Man_casual_3_F {scope=1;scopeCurator=1;};
	class C_Man_casual_3_F_tanoan: C_Man_casual_3_F {scope=1;scopeCurator=1;};
	class C_Man_casual_4_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_4_F_afro: C_Man_casual_4_F {scope=1;scopeCurator=1;};
	class C_Man_casual_4_F_euro: C_Man_casual_4_F {scope=1;scopeCurator=1;};
	class C_Man_casual_4_F_asia: C_Man_casual_4_F {scope=1;scopeCurator=1;};
	class C_Man_casual_4_F_tanoan: C_Man_casual_4_F {scope=1;scopeCurator=1;};
	class C_Man_casual_5_F: C_Man_casual_4_F {scope=1;scopeCurator=1;};
	class C_Man_casual_5_F_afro: C_Man_casual_5_F {scope=1;scopeCurator=1;};
	class C_Man_casual_5_F_euro: C_Man_casual_5_F {scope=1;scopeCurator=1;};
	class C_Man_casual_5_F_asia: C_Man_casual_5_F {scope=1;scopeCurator=1;};
	class C_Man_casual_5_F_tanoan: C_Man_casual_5_F {scope=1;scopeCurator=1;};
	class C_Man_casual_6_F: C_Man_casual_4_F {scope=1;scopeCurator=1;};
	class C_Man_casual_6_F_afro: C_Man_casual_6_F {scope=1;scopeCurator=1;};
	class C_Man_casual_6_F_euro: C_Man_casual_6_F {scope=1;scopeCurator=1;};
	class C_Man_casual_6_F_asia: C_Man_casual_6_F {scope=1;scopeCurator=1;};
	class C_Man_casual_6_F_tanoan: C_Man_casual_6_F {scope=1;scopeCurator=1;};
	class AAA_System_01_base_F;
	class B_AAA_System_01_F: AAA_System_01_base_F {scope=1;scopeCurator=1;};
	class SAM_System_01_base_F;
	class B_SAM_System_01_F: SAM_System_01_base_F {scope=1;scopeCurator=1;};
	class SAM_System_02_base_F;
	class B_SAM_System_02_F: SAM_System_02_base_F {scope=1;scopeCurator=1;};
	class Plane_Fighter_01_Base_F;
	class B_Plane_Fighter_01_F: Plane_Fighter_01_Base_F {scope=1;scopeCurator=1;};
	class B_Plane_Fighter_01_Stealth_F: Plane_Fighter_01_Base_F {scope=1;scopeCurator=1;};
	class Plane_Fighter_02_Base_F;
	class O_Plane_Fighter_02_F: Plane_Fighter_02_Base_F {scope=1;scopeCurator=1;};
	class O_Plane_Fighter_02_Stealth_F: Plane_Fighter_02_Base_F {scope=1;scopeCurator=1;};
	class Plane_Fighter_04_Base_F;
	class I_Plane_Fighter_04_F: Plane_Fighter_04_Base_F {scope=1;scopeCurator=1;};
	class UAV_05_Base_F;
	class B_UAV_05_F: UAV_05_Base_F {scope=1;scopeCurator=1;};
	class B_Deck_Crew_F: B_Helipilot_F {scope=1;scopeCurator=1;};
	class B_Fighter_Pilot_F: B_Pilot_F {scope=1;scopeCurator=1;};
	class O_Fighter_Pilot_F: O_Pilot_F {scope=1;scopeCurator=1;};
	class I_Fighter_Pilot_F: I_pilot_F {scope=1;scopeCurator=1;};
	class B_Patrol_Soldier_TL_F: B_Soldier_TL_F {scope=1;scopeCurator=1;};
	class B_Patrol_Soldier_UAV_F: B_soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_Patrol_Soldier_M_F: B_soldier_M_F {scope=1;scopeCurator=1;};
	class B_Patrol_Medic_F: B_medic_F {scope=1;scopeCurator=1;};
	class B_Patrol_Soldier_AR_F: B_soldier_AR_F {scope=1;scopeCurator=1;};
	class B_Patrol_Soldier_MG_F: B_soldier_AR_F {scope=1;scopeCurator=1;};
	class B_Patrol_HeavyGunner_F: B_HeavyGunner_F {scope=1;scopeCurator=1;};
	class B_Patrol_Soldier_A_F: B_Soldier_A_F {scope=1;scopeCurator=1;};
	class B_Patrol_Soldier_AT_F: B_soldier_AT_F {scope=1;scopeCurator=1;};
	class B_Patrol_Engineer_F: B_engineer_F {scope=1;scopeCurator=1;};
	class C_IDAP_Offroad_01_F: Offroad_01_civil_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Offroad_02_unarmed_F: Offroad_02_unarmed_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Truck_02_F: Truck_02_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Truck_02_transport_F: Truck_02_transport_base_F {scope=1;scopeCurator=1;};
	class Truck_02_water_base_F;
	class C_IDAP_Truck_02_water_F: Truck_02_water_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_UGV_01_F: UGV_01_base_F {scope=1;scopeCurator=1;};
	class Van_02_transport_base_F;
	class C_Van_02_transport_F: Van_02_transport_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Van_02_transport_F: Van_02_transport_base_F {scope=1;scopeCurator=1;};
	class I_G_Van_02_transport_F: Van_02_transport_base_F {scope=1;scopeCurator=1;};
	class B_G_Van_02_transport_F: Van_02_transport_base_F {scope=1;scopeCurator=1;};
	class B_GEN_Van_02_transport_F: Van_02_transport_base_F {scope=1;scopeCurator=1;};
	class O_G_Van_02_transport_F: Van_02_transport_base_F {scope=1;scopeCurator=1;};
	class I_C_Van_02_transport_F: Van_02_transport_base_F {scope=1;scopeCurator=1;};
	class Van_02_vehicle_base_F;
	class C_Van_02_vehicle_F: Van_02_vehicle_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Van_02_vehicle_F: Van_02_vehicle_base_F {scope=1;scopeCurator=1;};
	class I_G_Van_02_vehicle_F: Van_02_vehicle_base_F {scope=1;scopeCurator=1;};
	class B_G_Van_02_vehicle_F: Van_02_vehicle_base_F {scope=1;scopeCurator=1;};
	class B_GEN_Van_02_vehicle_F: Van_02_vehicle_base_F {scope=1;scopeCurator=1;};
	class O_G_Van_02_vehicle_F: Van_02_vehicle_base_F {scope=1;scopeCurator=1;};
	class I_C_Van_02_vehicle_F: Van_02_vehicle_base_F {scope=1;scopeCurator=1;};
	class Van_02_medevac_base_F;
	class C_Van_02_medevac_F: Van_02_medevac_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Van_02_medevac_F: Van_02_medevac_base_F {scope=1;scopeCurator=1;};
	class Van_02_service_base_F;
	class C_Van_02_service_F: Van_02_service_base_F {scope=1;scopeCurator=1;};
	class B_Plane_CAS_01_Cluster_F: B_Plane_CAS_01_dynamicLoadout_F {scope=1;scopeCurator=1;};
	class O_Plane_CAS_02_Cluster_F: O_Plane_CAS_02_dynamicLoadout_F {scope=1;scopeCurator=1;};
	class I_Plane_Fighter_03_Cluster_F: I_Plane_Fighter_03_dynamicLoadout_F {scope=1;scopeCurator=1;};
	class B_Plane_Fighter_01_Cluster_F: B_Plane_Fighter_01_F {scope=1;scopeCurator=1;};
	class O_Plane_Fighter_02_Cluster_F: O_Plane_Fighter_02_F {scope=1;scopeCurator=1;};
	class I_Plane_Fighter_04_Cluster_F: I_Plane_Fighter_04_F {scope=1;scopeCurator=1;};
	class C_IDAP_Heli_Transport_02_F: Heli_Transport_02_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_UAV_01_F: UAV_01_base_F {scope=1;scopeCurator=1;};
	class UAV_06_base_F;
	class B_UAV_06_F: UAV_06_base_F {scope=1;scopeCurator=1;};
	class O_UAV_06_F: UAV_06_base_F {scope=1;scopeCurator=1;};
	class I_UAV_06_F: UAV_06_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_UAV_06_F: UAV_06_base_F {scope=1;scopeCurator=1;};
	class C_UAV_06_F: UAV_06_base_F {scope=1;scopeCurator=1;};
	class UAV_06_antimine_base_F;
	class C_IDAP_UAV_06_antimine_F: UAV_06_antimine_base_F {scope=1;scopeCurator=1;};
	class UAV_06_medical_base_F;
	class B_UAV_06_medical_F: UAV_06_medical_base_F {scope=1;scopeCurator=1;};
	class O_UAV_06_medical_F: UAV_06_medical_base_F {scope=1;scopeCurator=1;};
	class I_UAV_06_medical_F: UAV_06_medical_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_UAV_06_medical_F: UAV_06_medical_base_F {scope=1;scopeCurator=1;};
	class C_UAV_06_medical_F: UAV_06_medical_base_F {scope=1;scopeCurator=1;};
	class B_soldier_UAV_06_F: B_soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_soldier_UAV_06_medical_F: B_soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_T_soldier_UAV_06_F: B_T_Soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_T_soldier_UAV_06_medical_F: B_T_Soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_soldier_mine_F: B_soldier_exp_F {scope=1;scopeCurator=1;};
	class B_T_soldier_mine_F: B_T_Soldier_Exp_F {scope=1;scopeCurator=1;};
	class O_soldier_UAV_06_F: O_soldier_UAV_F {scope=1;scopeCurator=1;};
	class O_soldier_UAV_06_medical_F: O_soldier_UAV_F {scope=1;scopeCurator=1;};
	class O_T_soldier_UAV_06_F: O_T_Soldier_UAV_F {scope=1;scopeCurator=1;};
	class O_T_soldier_UAV_06_medical_F: O_T_Soldier_UAV_F {scope=1;scopeCurator=1;};
	class O_soldier_mine_F: O_soldier_exp_F {scope=1;scopeCurator=1;};
	class O_T_soldier_mine_F: O_T_Soldier_Exp_F {scope=1;scopeCurator=1;};
	class I_soldier_UAV_06_F: I_soldier_UAV_F {scope=1;scopeCurator=1;};
	class I_soldier_UAV_06_medical_F: I_soldier_UAV_F {scope=1;scopeCurator=1;};
	class I_soldier_mine_F: I_Soldier_exp_F {scope=1;scopeCurator=1;};
	class B_G_Story_Guerilla_01_F: B_G_Soldier_F {scope=1;scopeCurator=1;};
	class I_Story_Officer_01_F: I_officer_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_Base_F;
	class C_IDAP_Man_AidWorker_01_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_AidWorker_02_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_AidWorker_03_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_AidWorker_04_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_AidWorker_05_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_AidWorker_06_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_AidWorker_07_F: C_IDAP_Man_AidWorker_03_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_AidWorker_08_F: C_IDAP_Man_AidWorker_04_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_AidWorker_09_F: C_IDAP_Man_AidWorker_02_F {scope=1;scopeCurator=1;};
	class C_Man_ConstructionWorker_01_Red_F: C_Driver_1_F {scope=1;scopeCurator=1;};
	class C_Man_ConstructionWorker_01_Vrana_F: C_Man_ConstructionWorker_01_Red_F {scope=1;scopeCurator=1;};
	class C_Man_ConstructionWorker_01_Black_F: C_Man_ConstructionWorker_01_Red_F {scope=1;scopeCurator=1;};
	class C_Man_ConstructionWorker_01_Blue_F: C_Man_ConstructionWorker_01_Red_F {scope=1;scopeCurator=1;};
	class C_Paramedic_01_base_F;
	class C_Man_Paramedic_01_F: C_Paramedic_01_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_Paramedic_01_F: C_Paramedic_01_base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Pilot_01_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_Journalist_01_War_F: C_journalist_F {scope=1;scopeCurator=1;};
	class C_Man_UtilityWorker_01_F: Civilian_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_EOD_01_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_UAV_01_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_UAV_06_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_UAV_06_medical_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_Man_UAV_06_antimine_F: C_IDAP_Man_Base_F {scope=1;scopeCurator=1;};
	class C_Man_UAV_06_F: Civilian_F {scope=1;scopeCurator=1;};
	class C_Man_UAV_06_medical_F: Civilian_F {scope=1;scopeCurator=1;};
	class C_Man_Fisherman_01_F: Civilian_F {scope=1;scopeCurator=1;};
	class C_Man_Messenger_01_F: Civilian_F {scope=1;scopeCurator=1;};
	class C_Story_EOD_01_F: C_IDAP_Man_EOD_01_F {scope=1;scopeCurator=1;};
	class C_Story_Mechanic_01_F: Civilian_F {scope=1;scopeCurator=1;};
	class O_A_soldier_base_F;
	class O_A_soldier_F: O_A_soldier_base_F {scope=1;scopeCurator=1;};
	class O_A_soldier_TL_F: O_A_soldier_base_F {scope=1;scopeCurator=1;};
	class AFV_Wheeled_01_base_F;
	class B_AFV_Wheeled_01_cannon_F: AFV_Wheeled_01_base_F {scope=1;scopeCurator=1;};
	class B_T_AFV_Wheeled_01_cannon_F: AFV_Wheeled_01_base_F {scope=1;scopeCurator=1;};
	class AFV_Wheeled_01_up_base_F;
	class B_AFV_Wheeled_01_up_cannon_F: AFV_Wheeled_01_up_base_F {scope=1;scopeCurator=1;};
	class B_T_AFV_Wheeled_01_up_cannon_F: AFV_Wheeled_01_up_base_F {scope=1;scopeCurator=1;};
	class LT_01_AT_base_F;
	class I_LT_01_AT_F: LT_01_AT_base_F {scope=1;scopeCurator=1;};
	class LT_01_scout_base_F;
	class I_LT_01_scout_F: LT_01_scout_base_F {scope=1;scopeCurator=1;};
	class LT_01_AA_base_F;
	class I_LT_01_AA_F: LT_01_AA_base_F {scope=1;scopeCurator=1;};
	class LT_01_cannon_base_F;
	class I_LT_01_cannon_F: LT_01_cannon_base_F {scope=1;scopeCurator=1;};
	class MBT_04_cannon_base_F;
	class O_MBT_04_cannon_F: MBT_04_cannon_base_F {scope=1;scopeCurator=1;};
	class O_T_MBT_04_cannon_F: MBT_04_cannon_base_F {scope=1;scopeCurator=1;};
	class MBT_04_command_base_F;
	class O_MBT_04_command_F: MBT_04_command_base_F {scope=1;scopeCurator=1;};
	class O_T_MBT_04_command_F: MBT_04_command_base_F {scope=1;scopeCurator=1;};
	class B_soldier_LAT2_F: B_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_T_Soldier_LAT2_F: B_soldier_LAT2_F {scope=1;scopeCurator=1;};
	class B_CTRG_Soldier_LAT2_tna_F: B_CTRG_Soldier_F {scope=1;scopeCurator=1;};
	class I_G_Soldier_LAT2_F: I_G_Soldier_base_F {scope=1;scopeCurator=1;};
	class B_G_Soldier_LAT2_F: I_G_Soldier_LAT2_F {scope=1;scopeCurator=1;};
	class O_G_Soldier_LAT2_F: I_G_Soldier_LAT2_F {scope=1;scopeCurator=1;};
	class I_Soldier_LAT2_F: I_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_Soldier_HAT_F: O_Soldier_base_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_HAT_F: O_Soldier_HAT_F {scope=1;scopeCurator=1;};
	class O_Soldier_AHAT_F: O_Soldier_support_base_F {scope=1;scopeCurator=1;};
	class O_T_Soldier_AHAT_F: O_Soldier_AHAT_F {scope=1;scopeCurator=1;};
	class I_Story_Crew_F: I_crew_F {scope=1;scopeCurator=1;};
	class B_Ship_Gun_01_base_F;
	class B_Ship_Gun_01_F: B_Ship_Gun_01_base_F {scope=1;scopeCurator=1;};
	class B_Ship_MRLS_01_base_F;
	class B_Ship_MRLS_01_F: B_Ship_MRLS_01_base_F {scope=1;scopeCurator=1;};
	class Radar_System_01_base_F;
	class B_Radar_System_01_F: Radar_System_01_base_F {scope=1;scopeCurator=1;};
	class Radar_System_02_base_F;
	class O_Radar_System_02_F: Radar_System_02_base_F {scope=1;scopeCurator=1;};
	class SAM_System_03_base_F;
	class B_SAM_System_03_F: SAM_System_03_base_F {scope=1;scopeCurator=1;};
	class SAM_System_04_base_F;
	class O_SAM_System_04_F: SAM_System_04_base_F {scope=1;scopeCurator=1;};
	class I_E_Offroad_01_F: Offroad_01_military_base_F {scope=1;scopeCurator=1;};
	class Offroad_01_military_covered_base_F;
	class I_E_Offroad_01_covered_F: Offroad_01_military_covered_base_F {scope=1;scopeCurator=1;};
	class Offroad_01_military_comms_base_F;
	class I_E_Offroad_01_comms_F: Offroad_01_military_comms_base_F {scope=1;scopeCurator=1;};
	class B_GEN_Offroad_01_covered_F: Offroad_01_military_covered_base_F {scope=1;scopeCurator=1;};
	class B_GEN_Offroad_01_comms_F: Offroad_01_military_comms_base_F {scope=1;scopeCurator=1;};
	class C_Offroad_01_covered_F: Offroad_01_military_covered_base_F {scope=1;scopeCurator=1;};
	class C_Offroad_01_comms_F: Offroad_01_military_comms_base_F {scope=1;scopeCurator=1;};
	class I_E_Quadbike_01_F: Quadbike_01_base_F {scope=1;scopeCurator=1;};
	class Tractor_01_base_F;
	class C_Tractor_01_F: Tractor_01_base_F {scope=1;scopeCurator=1;};
	class Truck_01_flatbed_base_F;
	class B_Truck_01_flatbed_F: Truck_01_flatbed_base_F {scope=1;scopeCurator=1;};
	class B_T_Truck_01_flatbed_F: Truck_01_flatbed_base_F {scope=1;scopeCurator=1;};
	class Truck_01_cargo_base_F;
	class B_Truck_01_cargo_F: Truck_01_cargo_base_F {scope=1;scopeCurator=1;};
	class B_T_Truck_01_cargo_F: Truck_01_cargo_base_F {scope=1;scopeCurator=1;};
	class I_E_Truck_02_F: Truck_02_base_F {scope=1;scopeCurator=1;};
	class I_E_Truck_02_transport_F: Truck_02_transport_base_F {scope=1;scopeCurator=1;};
	class I_E_Truck_02_fuel_F: Truck_02_fuel_base_F {scope=1;scopeCurator=1;};
	class I_E_Truck_02_Ammo_F: Truck_02_Ammo_base_F {scope=1;scopeCurator=1;};
	class I_E_Truck_02_Box_F: Truck_02_box_base_F {scope=1;scopeCurator=1;};
	class I_E_Truck_02_Medical_F: Truck_02_medical_base_F {scope=1;scopeCurator=1;};
	class I_E_Truck_02_MRL_F: Truck_02_MRL_base_F {scope=1;scopeCurator=1;};
	class I_E_UGV_01_F: UGV_01_base_F {scope=1;scopeCurator=1;};
	class I_E_UGV_01_rcws_F: UGV_01_rcws_base_F {scope=1;scopeCurator=1;};
	class UGV_02_Science_Base_F;
	class B_UGV_02_Science_F: UGV_02_Science_Base_F {scope=1;scopeCurator=1;};
	class UGV_02_Demining_Base_F;
	class B_UGV_02_Demining_F: UGV_02_Demining_Base_F {scope=1;scopeCurator=1;};
	class O_UGV_02_Science_F: UGV_02_Science_Base_F {scope=1;scopeCurator=1;};
	class O_UGV_02_Demining_F: UGV_02_Demining_Base_F {scope=1;scopeCurator=1;};
	class I_UGV_02_Science_F: UGV_02_Science_Base_F {scope=1;scopeCurator=1;};
	class I_E_UGV_02_Science_F: UGV_02_Science_Base_F {scope=1;scopeCurator=1;};
	class I_UGV_02_Demining_F: UGV_02_Demining_Base_F {scope=1;scopeCurator=1;};
	class I_E_UGV_02_Demining_F: UGV_02_Demining_Base_F {scope=1;scopeCurator=1;};
	class C_IDAP_UGV_02_Demining_F: UGV_02_Demining_Base_F {scope=1;scopeCurator=1;};
	class I_E_Van_02_vehicle_F: Van_02_vehicle_base_F {scope=1;scopeCurator=1;};
	class I_E_Van_02_transport_F: Van_02_transport_base_F {scope=1;scopeCurator=1;};
	class I_E_Van_02_transport_MP_F: Van_02_transport_base_F {scope=1;scopeCurator=1;};
	class I_E_Van_02_medevac_F: Van_02_medevac_base_F {scope=1;scopeCurator=1;};
	class I_E_Static_AA_F: I_static_AA_F {scope=1;scopeCurator=1;};
	class I_E_Static_AT_F: I_static_AT_F {scope=1;scopeCurator=1;};
	class B_W_Static_Designator_01_F: Static_Designator_01_base_F {scope=1;scopeCurator=1;};
	class I_E_GMG_01_F: I_GMG_01_F {scope=1;scopeCurator=1;};
	class I_E_GMG_01_high_F: I_GMG_01_high_F {scope=1;scopeCurator=1;};
	class I_E_GMG_01_A_F: I_GMG_01_A_F {scope=1;scopeCurator=1;};
	class I_E_HMG_01_F: I_HMG_01_F {scope=1;scopeCurator=1;};
	class I_E_HMG_01_high_F: I_HMG_01_high_F {scope=1;scopeCurator=1;};
	class I_E_HMG_01_A_F: I_HMG_01_A_F {scope=1;scopeCurator=1;};
	class I_E_Mortar_01_F: I_Mortar_01_F {scope=1;scopeCurator=1;};
	class I_E_Radar_System_01_F: Radar_System_01_base_F {scope=1;scopeCurator=1;};
	class I_E_SAM_System_03_F: SAM_System_03_base_F {scope=1;scopeCurator=1;};
	class I_E_Heli_light_03_dynamicLoadout_F: Heli_light_03_dynamicLoadout_base_F {scope=1;scopeCurator=1;};
	class I_E_Heli_light_03_unarmed_F: Heli_light_03_unarmed_base_F {scope=1;scopeCurator=1;};
	class I_E_UAV_01_F: UAV_01_base_F {scope=1;scopeCurator=1;};
	class I_E_UAV_06_F: UAV_06_base_F {scope=1;scopeCurator=1;};
	class I_E_UAV_06_medical_F: UAV_06_medical_base_F {scope=1;scopeCurator=1;};
	class I_E_APC_tracked_03_base_F;
	class I_E_APC_tracked_03_cannon_F: I_E_APC_tracked_03_base_F {scope=1;scopeCurator=1;};
	class C_scientist_01_base_F;
	class C_scientist_01_formal_F: C_scientist_01_base_F {scope=1;scopeCurator=1;};
	class C_scientist_02_formal_F: C_scientist_01_base_F {scope=1;scopeCurator=1;};
	class C_scientist_01_informal_F: C_scientist_01_base_F {scope=1;scopeCurator=1;};
	class C_scientist_02_informal_F: C_scientist_01_base_F {scope=1;scopeCurator=1;};
	class C_man_enoch_base_F;
	class C_Man_1_enoch_F: C_man_enoch_base_F {scope=1;scopeCurator=1;};
	class C_Man_2_enoch_F: C_man_enoch_base_F {scope=1;scopeCurator=1;};
	class C_Man_3_enoch_F: C_man_enoch_base_F {scope=1;scopeCurator=1;};
	class C_Man_4_enoch_F: C_man_enoch_base_F {scope=1;scopeCurator=1;};
	class C_Man_5_enoch_F: C_man_enoch_base_F {scope=1;scopeCurator=1;};
	class C_Man_6_enoch_F: C_man_enoch_base_F {scope=1;scopeCurator=1;};
	class C_Farmer_01_enoch_F: C_man_enoch_base_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_A_F: B_Soldier_A_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_AAR_F: B_soldier_AAR_F {scope=1;scopeCurator=1;};
	class B_W_Support_AMG_F: B_support_AMG_F {scope=1;scopeCurator=1;};
	class B_W_Support_AMort_F: B_support_AMort_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_AAA_F: B_soldier_AAA_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_AAT_F: B_soldier_AAT_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_AR_F: B_soldier_AR_F {scope=1;scopeCurator=1;};
	class B_W_Medic_F: B_medic_F {scope=1;scopeCurator=1;};
	class B_W_Crew_F: B_crew_F {scope=1;scopeCurator=1;};
	class B_W_Engineer_F: B_engineer_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_Exp_F: B_soldier_exp_F {scope=1;scopeCurator=1;};
	class B_W_soldier_mine_F: B_W_Soldier_Exp_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_GL_F: B_Soldier_GL_F {scope=1;scopeCurator=1;};
	class B_W_Support_GMG_F: B_support_GMG_F {scope=1;scopeCurator=1;};
	class B_W_Support_MG_F: B_support_MG_F {scope=1;scopeCurator=1;};
	class B_W_Support_Mort_F: B_support_Mort_F {scope=1;scopeCurator=1;};
	class B_W_Helicrew_F: B_helicrew_F {scope=1;scopeCurator=1;};
	class B_W_Helipilot_F: B_Helipilot_F {scope=1;scopeCurator=1;};
	class B_W_soldier_M_F: B_soldier_M_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_AA_F: B_soldier_AA_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_AT_F: B_soldier_AT_F {scope=1;scopeCurator=1;};
	class B_W_Officer_F: B_officer_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_Repair_F: B_soldier_repair_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_F: B_Soldier_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_LAT_F: B_soldier_LAT_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_LAT2_F: B_soldier_LAT2_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_SL_F: B_Soldier_SL_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_TL_F: B_Soldier_TL_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_CBRN_F: B_W_Soldier_F {scope=1;scopeCurator=1;};
	class B_W_RadioOperator_F: B_W_Soldier_F {scope=1;scopeCurator=1;};
	class B_W_Survivor_F: B_W_Soldier_F {scope=1;scopeCurator=1;};
	class B_soldier_UGV_02_Science_F: B_soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_soldier_UGV_02_Demining_F: B_soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_UAV_F: B_soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_W_soldier_UGV_02_Science_F: B_W_Soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_W_soldier_UGV_02_Demining_F: B_W_Soldier_UAV_F {scope=1;scopeCurator=1;};
	class B_W_Soldier_unarmed_F: B_W_Soldier_F {scope=1;scopeCurator=1;};
	class O_R_Soldier_Base_F;
	class O_R_Soldier_TL_F: O_R_Soldier_Base_F {scope=1;scopeCurator=1;};
	class O_R_Soldier_GL_F: O_R_Soldier_Base_F {scope=1;scopeCurator=1;};
	class O_R_soldier_exp_F: O_R_Soldier_Base_F {scope=1;scopeCurator=1;};
	class O_R_Soldier_AR_F: O_R_Soldier_Base_F {scope=1;scopeCurator=1;};
	class O_R_soldier_M_F: O_R_Soldier_Base_F {scope=1;scopeCurator=1;};
	class O_R_medic_F: O_R_Soldier_Base_F {scope=1;scopeCurator=1;};
	class O_R_Soldier_LAT_F: O_R_Soldier_Base_F {scope=1;scopeCurator=1;};
	class O_R_JTAC_F: O_R_Soldier_Base_F {scope=1;scopeCurator=1;};
	class O_R_Soldier_recon_base;
	class O_R_recon_TL_F: O_R_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_R_recon_exp_F: O_R_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_R_recon_AR_F: O_R_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_R_recon_M_F: O_R_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_R_recon_medic_F: O_R_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_R_recon_GL_F: O_R_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_R_recon_LAT_F: O_R_Soldier_recon_base {scope=1;scopeCurator=1;};
	class O_R_recon_JTAC_F: O_R_Soldier_recon_base {scope=1;scopeCurator=1;};
	class I_E_Soldier_base_F;
	class I_E_Soldier_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_unarmed_F: I_E_Soldier_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_A_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_AAR_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_AR_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_lite_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_GL_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_soldier_M_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Officer_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_SL_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_TL_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Survivor_F: I_E_Soldier_F {scope=1;scopeCurator=1;};
	class I_E_RadioOperator_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_AA_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_AT_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_LAT_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_LAT2_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_AAA_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_AAT_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Support_GMG_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Support_MG_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Support_Mort_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Support_AMG_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Support_AMort_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_Pathfinder_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Engineer_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_Exp_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_soldier_Mine_F: I_E_Soldier_Exp_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_Repair_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_CBRN_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Scientist_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Scientist_Unarmed_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Medic_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_MP_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Crew_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Helipilot_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Helicrew_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_UAV_F: I_E_Soldier_base_F {scope=1;scopeCurator=1;};
	class I_E_soldier_UAV_06_F: I_E_Soldier_UAV_F {scope=1;scopeCurator=1;};
	class I_E_soldier_UAV_06_medical_F: I_E_Soldier_UAV_F {scope=1;scopeCurator=1;};
	class I_E_soldier_UGV_02_Science_F: I_E_Soldier_UAV_F {scope=1;scopeCurator=1;};
	class I_E_soldier_UGV_02_Demining_F: I_E_Soldier_UAV_F {scope=1;scopeCurator=1;};
	class I_E_Soldier_universal_F: I_E_Soldier_F {scope=1;scopeCurator=1;};
	class O_R_Patrol_Soldier_TL_F: O_R_Soldier_TL_F {scope=1;scopeCurator=1;};
	class O_R_Patrol_Soldier_AR_F: O_R_Soldier_AR_F {scope=1;scopeCurator=1;};
	class O_R_Patrol_Soldier_AR2_F: O_R_Soldier_AR_F {scope=1;scopeCurator=1;};
	class O_R_Patrol_Soldier_GL_F: O_R_Soldier_GL_F {scope=1;scopeCurator=1;};
	class O_R_Patrol_Soldier_A_F: O_R_Soldier_Base_F {scope=1;scopeCurator=1;};
	class O_R_Patrol_Soldier_M_F: O_R_soldier_M_F {scope=1;scopeCurator=1;};
	class O_R_Patrol_Soldier_M2_F: O_R_soldier_M_F {scope=1;scopeCurator=1;};
	class O_R_Patrol_Soldier_Medic: O_R_medic_F {scope=1;scopeCurator=1;};
	class O_R_Patrol_Soldier_Engineer_F: O_R_Soldier_Base_F {scope=1;scopeCurator=1;};
	class O_R_Patrol_Soldier_LAT_F: O_R_Soldier_LAT_F {scope=1;scopeCurator=1;};
	class I_L_Uniform_01_camo_F: I_G_Soldier_LAT_F {scope=1;scopeCurator=1;};
	class I_L_Uniform_01_deserter_F: I_G_Soldier_F {scope=1;scopeCurator=1;};
	class I_L_Soldier_Base_F;
	class I_L_Looter_Pistol_F: I_L_Soldier_Base_F {scope=1;scopeCurator=1;};
	class I_L_Looter_SG_F: I_L_Soldier_Base_F {scope=1;scopeCurator=1;};
	class I_L_Looter_Rifle_F: I_L_Soldier_Base_F {scope=1;scopeCurator=1;};
	class I_L_Looter_SMG_F: I_L_Soldier_Base_F {scope=1;scopeCurator=1;};
	class I_L_Criminal_SG_F: I_L_Soldier_Base_F {scope=1;scopeCurator=1;};
	class I_L_Criminal_SMG_F: I_L_Soldier_Base_F {scope=1;scopeCurator=1;};
	class I_L_Hunter_F: I_L_Soldier_Base_F {scope=1;scopeCurator=1;};
	class SyndikatSoldier_Default: I_C_Soldier_Para_1_F {scope=1;scopeCurator=1;};
	class O_GEN_Soldier_F: B_GEN_Soldier_F {scope=1;scopeCurator=1;};
	class O_GEN_Commander_F: B_GEN_Commander_F {scope=1;scopeCurator=1;};
	class C_Man_formal_1_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_formal_1_F_afro: C_Man_formal_1_F {scope=1;scopeCurator=1;};
	class C_Man_formal_1_F_euro: C_Man_formal_1_F {scope=1;scopeCurator=1;};
	class C_Man_formal_1_F_asia: C_Man_formal_1_F {scope=1;scopeCurator=1;};
	class C_Man_formal_1_F_tanoan: C_Man_formal_1_F {scope=1;scopeCurator=1;};
	class C_Man_formal_2_F: C_Man_formal_1_F {scope=1;scopeCurator=1;};
	class C_Man_formal_2_F_afro: C_Man_formal_2_F {scope=1;scopeCurator=1;};
	class C_Man_formal_2_F_euro: C_Man_formal_2_F {scope=1;scopeCurator=1;};
	class C_Man_formal_2_F_asia: C_Man_formal_2_F {scope=1;scopeCurator=1;};
	class C_Man_formal_2_F_tanoan: C_Man_formal_2_F {scope=1;scopeCurator=1;};
	class C_Man_formal_3_F: C_Man_formal_1_F {scope=1;scopeCurator=1;};
	class C_Man_formal_3_F_afro: C_Man_formal_3_F {scope=1;scopeCurator=1;};
	class C_Man_formal_3_F_euro: C_Man_formal_3_F {scope=1;scopeCurator=1;};
	class C_Man_formal_3_F_asia: C_Man_formal_3_F {scope=1;scopeCurator=1;};
	class C_Man_formal_3_F_tanoan: C_Man_formal_3_F {scope=1;scopeCurator=1;};
	class C_Man_formal_4_F: C_Man_formal_1_F {scope=1;scopeCurator=1;};
	class C_Man_formal_4_F_afro: C_Man_formal_4_F {scope=1;scopeCurator=1;};
	class C_Man_formal_4_F_euro: C_Man_formal_4_F {scope=1;scopeCurator=1;};
	class C_Man_formal_4_F_asia: C_Man_formal_4_F {scope=1;scopeCurator=1;};
	class C_Man_formal_4_F_tanoan: C_Man_formal_4_F {scope=1;scopeCurator=1;};
	class C_Man_smart_casual_1_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_smart_casual_1_F_afro: C_Man_smart_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_smart_casual_1_F_euro: C_Man_smart_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_smart_casual_1_F_asia: C_Man_smart_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_smart_casual_1_F_tanoan: C_Man_smart_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_smart_casual_2_F: C_Man_smart_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_smart_casual_2_F_afro: C_Man_smart_casual_2_F {scope=1;scopeCurator=1;};
	class C_Man_smart_casual_2_F_euro: C_Man_smart_casual_2_F {scope=1;scopeCurator=1;};
	class C_Man_smart_casual_2_F_asia: C_Man_smart_casual_2_F {scope=1;scopeCurator=1;};
	class C_Man_smart_casual_2_F_tanoan: C_Man_smart_casual_2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_4_v2_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_4_v2_F_afro: C_Man_casual_4_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_4_v2_F_euro: C_Man_casual_4_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_4_v2_F_asia: C_Man_casual_4_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_4_v2_F_tanoan: C_Man_casual_4_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_5_v2_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_5_v2_F_afro: C_Man_casual_5_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_5_v2_F_euro: C_Man_casual_5_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_5_v2_F_asia: C_Man_casual_5_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_5_v2_F_tanoan: C_Man_casual_5_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_6_v2_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_6_v2_F_afro: C_Man_casual_6_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_6_v2_F_euro: C_Man_casual_6_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_6_v2_F_asia: C_Man_casual_6_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_6_v2_F_tanoan: C_Man_casual_6_v2_F {scope=1;scopeCurator=1;};
	class C_Man_casual_7_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_7_F_afro: C_Man_casual_7_F {scope=1;scopeCurator=1;};
	class C_Man_casual_7_F_euro: C_Man_casual_7_F {scope=1;scopeCurator=1;};
	class C_Man_casual_7_F_asia: C_Man_casual_7_F {scope=1;scopeCurator=1;};
	class C_Man_casual_7_F_tanoan: C_Man_casual_7_F {scope=1;scopeCurator=1;};
	class C_Man_casual_8_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_8_F_afro: C_Man_casual_8_F {scope=1;scopeCurator=1;};
	class C_Man_casual_8_F_euro: C_Man_casual_8_F {scope=1;scopeCurator=1;};
	class C_Man_casual_8_F_asia: C_Man_casual_8_F {scope=1;scopeCurator=1;};
	class C_Man_casual_8_F_tanoan: C_Man_casual_8_F {scope=1;scopeCurator=1;};
	class C_Man_casual_9_F: C_Man_casual_1_F {scope=1;scopeCurator=1;};
	class C_Man_casual_9_F_afro: C_Man_casual_9_F {scope=1;scopeCurator=1;};
	class C_Man_casual_9_F_euro: C_Man_casual_9_F {scope=1;scopeCurator=1;};
	class C_Man_casual_9_F_asia: C_Man_casual_9_F {scope=1;scopeCurator=1;};
	class C_Man_casual_9_F_tanoan: C_Man_casual_9_F {scope=1;scopeCurator=1;};
	class B_Officer_Parade_F: B_officer_F {scope=1;scopeCurator=1;};
	class B_Officer_Parade_Veteran_F: B_Officer_Parade_F {scope=1;scopeCurator=1;};
	class I_Officer_Parade_F: I_officer_F {scope=1;scopeCurator=1;};
	class I_Officer_Parade_Veteran_F: I_Officer_Parade_F {scope=1;scopeCurator=1;};
	class I_E_Officer_Parade_F: I_E_Officer_F {scope=1;scopeCurator=1;};
	class I_E_Officer_Parade_Veteran_F: I_E_Officer_Parade_F {scope=1;scopeCurator=1;};
	class O_Officer_Parade_F: O_officer_F {scope=1;scopeCurator=1;};
	class O_Officer_Parade_Veteran_F: O_Officer_Parade_F {scope=1;scopeCurator=1;};
	
	// 2.14 update
	class O_MBT_02_railgun_base_F;
	class O_MBT_02_railgun_F: O_MBT_02_railgun_base_F {scope=1;scopeCurator=1;};
	class O_T_MBT_02_railgun_ghex_F:O_MBT_02_railgun_base_F {scope=1;scopeCurator=1;};
};

